### ISSUE TITLE
one broken link

### ISSUE THREAD

**Issue by pascalandy** [prakhar1989/docker-curriculum#10]
Hey Prakhar,

On the page: http://prakhar.me/docker-curriculum/ the picture under section _3.1 SF Food Trucks_ is not appearing. Put the absolute URL :)

Cheers!
Pascal

**Comment by prakhar1989** [comment]
Hey Pascal,

I can see the image appearing correctly for me and the `img` tag does point to the [absolute](https://raw.githubusercontent.com/prakhar1989/FoodTrucks/master/shot.png) url.  You might want to refresh the page and check again? :)

Thanks!

**Comment by pascalandy** [comment]
Well it loads normally now. So I guess this was a simple glitch on my side. Forget this :)

Also, thank you very much for the tutorial. I'm grateful for having it. Very well structured Sir. 

Cheers!
Pascal

**Comment by prakhar1989** [comment]
Thanks for your kind words, Pascal. Glad you find the tutorial useful :)
