### ISSUE TITLE
Issue with tutorial step in section 3.1

### ISSUE THREAD

**Issue by jportill13** [prakhar1989/docker-curriculum#105]
Great beginners tutorial! I do have an observation though

The tutorial section 3.1 does not mention to get the source for the flask application, it only mentions to create a Dockerfile:

"While we are at it, let's get our Flask container running too. But before we get to that, we need a Dockerfile. "

Once the file is created it has references to the folder flask-app

ADD flask-app /opt/flask-app

But if you don't do a git clone of the project beforehand the docker build process will fail looking for this folder. I think that the tutorial should mention to download the foodtrucks app from git

git clone https://github.com/prakhar1989/FoodTrucks

and from there the Dockerfile can be modified or the docker build command can be run from there.

**Comment by rodriguesalex** [comment]
In addition to that, the following instruction is not clear
"
- Increase the memory size of your docker-machine instance to at least 2gb.
- Do an SSH in your docker-machine instance by docker-machine ssh and run this command sysctl -w vm.max_map_count=262144. This will fix the max virtual memory areas error.
"

Is docker-machine the same as the docker container just created for elasticsearch? What is the command o increase the memory size of the docker-machine?

**Comment by samdoidge** [comment]
Also ran into this - thank you!

**Comment by prakhar1989** [comment]
Clarified this in the tutorial. Thanks for bringing it up!
