### ISSUE TITLE
"exec format error"

### ISSUE THREAD

**Issue by EyeBool** [prakhar1989/docker-curriculum#107]
When I run (Docker version 18.02.0-ce, build fc4de44, running on a Raspberry Pi 3)
```
sudo docker run -p 8888:80 prakhar1989/static-site
```
I get
```
standard_init_linux.go:195: exec user process caused "exec format error"
```

**Comment by prakhar1989** [comment]
These images are not compiled for ARM, which is why you're getting this issue. Since I don't have a Raspberry Pi I'm afraid I can't test this out. I'd recommend you use the arm base images and build out the static-site container. More info here: https://blog.alexellis.io/5-things-docker-rpi/
