### ISSUE TITLE
About definition of base images

### ISSUE THREAD

**Issue by danielhamngren** [prakhar1989/docker-curriculum#11]
Thank you for a very nice tutorial!

I got a bit confused about the definition of base images, in your tutorial it is written:

An important distinction to be aware of when it comes to images is between base and user images.

- **Base images** are images that officially maintained and supported by the folks at Docker. These are typically one word long. In the list of images above, the python, ubuntu, busybox and hello-world images are base images.

- **User images** are images created and shared by users like you and me. They build on base images and add additional functionality. Typically these are formatted as user/image-name.

But this is different from the definition in the docker glossary: 
> An image that has no parent is a base image - [docker glossary](https://docs.docker.com/engine/reference/glossary/#base-image)

I think you are confusing official images, (the ones that are collected [here](https://github.com/docker-library/official-images)) with base images. It seems that some of the official images are base images but not all (for example golang or buildpack-deps).

It is also possible to create your own base images, [as shown in this guide.](https://docs.docker.com/engine/userguide/eng-image/baseimages/)

I suggest the following change:

An important distinction to be aware of when it comes to images is between base and child images.

- **Base images** are images that has no parent image, usually images with an OS like ubuntu, busybox or debian.

- **Child images** are images that build on base images and add additional functionality.

Then there are two more types of images that can be both base and child images, they are official and user images.

- **Official images** are images that officially maintained and supported by the folks at Docker. These are typically one word long. In the list of images above, the python, ubuntu, busybox and hello-world images are official images.

- **User images** are images created and shared by users like you and me. Typically these are formatted as user/image-name.

**Comment by prakhar1989** [comment]
Hey Daniel!

Thanks for pointing this out. You're absolutely right - I should've been clearer in my distinction of base and official images. As you suggested, I've made the changes and deployed a fresh version. 

Thanks for your input again :+1:

**Comment by danielhamngren** [comment]
No worries, I'm glad to help :-)

Again, thank you for the tutorial :+1:
