### ISSUE TITLE
Section 3.3 "ping es" doesn't work on Mac

### ISSUE THREAD

**Issue by annafock** [prakhar1989/docker-curriculum#110]
Hi, thanks a lot for a very informative and easy-to-follow tutorial. 

I'm running Docker from Mac Os Sierra. 
Recreate problem:
root@8dc63fa98134:/opt/flask-app# ping es
bash: ping: command not found

I read up and it's clear that ping is not supported on Mac, and the official page lists a few workarounds. A comment about what type of workarounds would be useful for the example in the tutorial would be much appreciated. 
Thanks again!

**Comment by prakhar1989** [comment]
Oh that's weird. I tried it on Mac OS Catalina, and `ping` seems to be available. Anyway, I will update the tutorial with this info. Thanks!
