### ISSUE TITLE
Terminology section links to legacy tool Kitematic

### ISSUE THREAD

**Issue by JoFAM** [prakhar1989/docker-curriculum#114]
Section 1.2 Terminology contains the following line : 

> Docker Client - The command line tool that allows the user to interact with the daemon. More generally, there can be other forms of clients too - such as Kitematic which provide a GUI to the users.

Kitematic is a legacy tool (see website) and users are strongly recommended to update to Docker for Mac or Docker for Windows if their system allows it. This needs updating.

**Comment by prakhar1989** [comment]
The website https://kitematic.com/ doesnt seem to indicate that the tool is deprecated. Thanks for bringing it up!
