### ISSUE TITLE
"npm install" is taking too long to complete.

### ISSUE THREAD

**Issue by mycode101** [prakhar1989/docker-curriculum#115]
Hi,

Hope you are doing good.

I am following your beginner guide on Docker. Thank you for the post.

"npm install" is taking too long to complete. i leave it run the whole night and it still is doing.

Could you advise me how to fix it.

Thanks

Sam

**Comment by prakhar1989** [comment]
Where are you running `npm install` from? It is happening when you're trying to build the image?
