### ISSUE TITLE
NoCredentialProviders: no valid providers in chain.

### ISSUE THREAD

**Issue by mark-stephenson-** [prakhar1989/docker-curriculum#118]
Struggling to get the ecs-cli call to work.  Ive tried a few variations of keypair location but its not working.  I'm getting the following:

> Marks-MBP:FoodTrucks mark$ ecs-cli up --keypair ~/.aws/docker-curriculum.pem --capability-iam --size 2 --instance-type t2.micro
> FATA[0005] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
> 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Any suggestions?

**Comment by mark-stephenson-** [comment]
Ok, this wasnt actually an issue with the keypair;

Basically you need to have an access key set up with adequate permissions to use the API.  Might be worth mentioning in the docs?

**Comment by phuwin** [comment]
@mark-stephenson- how do you solve this. I dont understand this. How do you have a key that can use the API?
