### ISSUE TITLE
Please update guide to say that ECS CLI is supported by Windows

### ISSUE THREAD

**Issue by trentet** [prakhar1989/docker-curriculum#121]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html

ECS CLI is now supported on Windows, as detailed in the link above. Section 3.4 of the guide currently says that it is not supported for Windows. Additionally, it doesn't tell you the required steps to configure the aws client to allow you to use the following command: ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro

I had to google the error that appeared in order to figure out that I needed to create a user, add them to a group, and run the aws configure command with all of the necessary information.

**Comment by phuwin** [comment]
@trentet Could you provide the aws configure command that you used?

**Comment by trentet** [comment]
@phuwin as my OP stated, I figured out the solution 5 months ago. I am not really asking for a solution myself, I’m asking for the guide I linked in my OP to be updated to include the solution.
