### ISSUE TITLE
lstat requirements.txt: no such file or directory

### ISSUE THREAD

**Issue by nmckey** [prakhar1989/docker-curriculum#124]
Hi I keep getting the error when I run 

"docker build -t myname/catnip .   "  from within the root of the docker-curriculum app.  Is the requirements.txt file something that needs to be on my local machine?

Command Output below:
Step 1 : FROM python:3-onbuild
Executing 3 build triggers...
Step 1 : COPY requirements.txt /usr/src/app/

**Comment by zhanglanqing** [comment]
same problem, how did you fix it?

**Comment by zhanglanqing** [comment]
same problem, how did you fix it? @nmckey

**Comment by prakhar1989** [comment]
Yes, you need to `cd` into the `flask-app` folder. Clarified this a bit better in the doc.
