### ISSUE TITLE
Where does the 192.168.99.100 come from?

### ISSUE THREAD

**Issue by CallMeZhou** [prakhar1989/docker-curriculum#125]
Your docker tutorial is great! I'm a beginner following your tutorial to learn docker. However, in the random cat example, where does the 192.168.99.100 come from?? and neither does this address work in my browser.

I saw it says it was running on http://0.0.0.0, so I tried http://0.0.0.0:8888, this worked.

Bye the way, your gif links seem to be broken.

**Comment by ken-gerada-congrego** [comment]
I'm guessing that if you use docker-toolbox instead of docker the default docker-machine will have a driver with a default IP of 192.168.99.100.
