### ISSUE TITLE
Foodtrucks Dockerfile - Does it need an update?

### ISSUE THREAD

**Issue by salvillalon45** [prakhar1989/docker-curriculum#131]
Hello, 

Thanks again for doing this great tutorial!

I just have a question. I been trying to build the Dockerfile but it will not let me. It gives me the errors attached in the picture. https://drive.google.com/file/d/1yM8c96Wedo97s7AXPN4wwMh_B4ANlXz5/view?usp=sharing

Also, when I try doing curl 0.0.0.0:9200 it says that the Address is not available.
https://drive.google.com/file/d/1VBdE9hZf9rQUEgxewWhOVHTSeTW2ZMnr/view?usp=sharing

Any help will be appreciated as I really want to finish this tutorial. 

Thank you.

**Comment by prakhar1989** [comment]
Updated now. Let me if you are still seeing issues.
