### ISSUE TITLE
prakhar1989/static-site repository does not exist

### ISSUE THREAD

**Issue by willim32533** [prakhar1989/docker-curriculum#135]
Despite being logged in successfully using docker run rakhar1989/static-site results in this error:

C:\WINDOWS\system32>docker run rakhar1989/static-site
Unable to find image 'rakhar1989/static-site:latest' locally
docker: Error response from daemon: pull access denied for rakhar1989/static-site, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by prakhar1989** [comment]
It should be 

```
$ docker run prakhar1989/static-site
```

https://hub.docker.com/r/prakhar1989/static-site/
