### ISSUE TITLE
Add ElasticSearch 'Out of Memory' info to the curriculum

### ISSUE THREAD

**Issue by palerdot** [prakhar1989/docker-curriculum#148]
I was running docker inside a vagrant machine and I encountered JVM error when trying to run the `elasticsearch` container. Following fix - https://github.com/elastic/elasticsearch-docker/issues/43#issuecomment-289377878 helped me to get through the issue. It will be better to add this as some kind of footnote somewhere.

**Comment by prakhar1989** [comment]
Good call - added a note
