### ISSUE TITLE
'docker network' provides name resolution using DNS instead of entries in /etc/hosts

### ISSUE THREAD

**Issue by pavdmyt** [prakhar1989/docker-curriculum#15]
Hi,

I went through tutorial with `Docker version 1.11.00`. In section *3.2 Docker Network* we creating new container with `--net=foodtrucks` and then examining `/etc/hosts` to make sure that appropriate name resolutions are added to the `hosts` file:

```
$ docker run -it --rm --net foodtrucks prakhar1989/foodtrucks-web bash
root@53af252b771a:/opt/flask-app# cat /etc/hosts
172.18.0.3  53af252b771a
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.2  es
172.18.0.2  es.foodtrucks
```

However, in newer versions of Docker [name resolution is done using DNS](https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-in-user-defined-networks). So, there will be no additional entries in the `hosts` file. Instead, DNS server IP will be added to `/etc/resolv.conf`:

```
root@56148395930d:/opt/flask-app# cat /etc/resolv.conf
search synapse.com
nameserver 127.0.0.11
options ndots:0
```
To make sure this works:

```
root@56148395930d:/opt/flask-app# ping es
PING es (172.18.0.2) 56(84) bytes of data.
64 bytes from es.foodtrucks (172.18.0.2): icmp_seq=1 ttl=64 time=0.092 ms
64 bytes from es.foodtrucks (172.18.0.2): icmp_seq=2 ttl=64 time=0.122 ms
64 bytes from es.foodtrucks (172.18.0.2): icmp_seq=3 ttl=64 time=0.117 ms
64 bytes from es.foodtrucks (172.18.0.2): icmp_seq=4 ttl=64 time=0.122 ms
^C
--- es ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 0.092/0.113/0.122/0.014 ms
```

**Comment by prakhar1989** [comment]
Oh! Thanks for letting me know - I'll update this in the tutorial :)

**Comment by salex89** [comment]
Just be careful, ECS does not yet support docker-compose version 2 files.

**Comment by prakhar1989** [comment]
Just updated the tutorial with this information! Thanks!
