### ISSUE TITLE
Error when creating cloud formation template using the ECS CLI

### ISSUE THREAD

**Issue by tobitech** [prakhar1989/docker-curriculum#150]
I get this error when I run the ECS CLI command 
`ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro`
`FATA[0005] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors`

**Comment by scsherwood** [comment]
Did everything in step two above and it still gives me the same error.

**Comment by paulolorenzobasilio** [comment]
UP. It still gives me the same error.

**Comment by joereg4** [comment]
Were you able to run `aws configure` and get it to prompt you for the 4 items needed?  I had to run `aws2 configure` but was able to gather the required inputs and get it to work.

AWS provides this as an example of what you will be prompted for substituting the Access Key ID and Secret Key provided in the My Account > Security Credentials > Access Keys section:
```
AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
Default region name [None]: us-west-2
Default output format [None]: json
```
