### ISSUE TITLE
Add proper shutdown and deleting of ECS cluster

### ISSUE THREAD

**Issue by JDeanThomas** [prakhar1989/docker-curriculum#154]
If you don't remove the task definitions, even if you shutdown and delete the cluster, the instances will continue to run, and reboot after any attempt to kill them after you're alerted to a month later via a billing statement.

Jason

**Comment by NathanMaton** [comment]
I agree this would be nice to have as someone who just finished the tutorial.  

But to your point about the instances, couldn't you just also remove them from your EC2 dashboard to avoid this issue?

**Comment by prakhar1989** [comment]
AFAIK `ecs-cli down -force` takes care of that - after running the command, I checked that none of my EC2 instances are running. 

I've added instructions for cleanup for both beanstalk and ECS 

![image](https://user-images.githubusercontent.com/649249/79702085-f0626500-8256-11ea-88fd-ce4c2e5d6d26.png)
