### ISSUE TITLE
Awesome Tutorial "Docker-Curriculum"

### ISSUE THREAD

**Issue by sanotto** [prakhar1989/docker-curriculum#157]
You stated your goal to "I want this tutorial to be one of the best introductory tutorials on the web". And you nailed it. Awesome tutorial,  perfectly clear, step by step carefully explained, and (a personal grudge of mine) no videos! just text ! so I'm able to follow it a my own pace. I'm recommending it to my fellows coworkers. Congratulations for a work well done and thank you very much.

**Comment by evenbrenden** [comment]
Second this! Pretty flawless and very rewarding walkthrough. Had some problems with `ecs-cli`, but as usual it's just because the instructions were not followed carefully enough. Thanks!

**Comment by prakhar1989** [comment]
Thank you for the kind words!
