### ISSUE TITLE
Unable to access 192.168.99.100 on MAC

### ISSUE THREAD

**Issue by ritu2012** [prakhar1989/docker-curriculum#158]
Hi, 
Your tutorials are good for a beginner looking to understand docker. 
I cannot understand how come 192.168.99.100 IP comes in picture. What is its use ?
I am bit confused about IPs usage in MAC.
and I am getting a strange behaviour, I run the command docker run -p 8888:5000 rituka/cat
and IP http://0.0.0.0:8888 gives me the cat gif of the day. 
Another strange thing is I already stopped  the container nginx
sometimes  http://192.168.99.100:8888 gives me 
Hello Docker!This is being served from a docker container running Nginx. and sometimes it gives server error.

**Comment by prakhar1989** [comment]
Hi, the 192.. ip is from yesteryears but now its no longer required. I've changed the screenshots to correctly reflect localhost or `0.0.0.0` as you have rightly guessed.
