### ISSUE TITLE
[minor] docker network section script issue re es - stop followed by run without rm

### ISSUE THREAD

**Issue by eidgenossen** [prakhar1989/docker-curriculum#160]
In the Docker Network section when it comes time to stop the es container running under the default bridge and start it again in the newly defined foodtrucks-net, the script starts...

docker run -d --name es -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.3.2

in docker v 18.09 (at least this results in the following error)

paul@xxxxxxxxxx:~/FoodTrucks$ docker run -d --name es --net foodtrucks-net -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.3.2
docker: Error response from daemon: Conflict. The container name "/es" is already in use by container "c00e3a4dc0f711dcdf89ee19f05e3b6a61c8dd6d8c4c5300419e260b2bf7e7d5". You have to remove (or rename) that container to be able to reuse that name.

need to run docker rm es before that new run command.

**Comment by prakhar1989** [comment]
Fixed in #161
