### ISSUE TITLE
I can still run "echo" after having removed the "bin" folder

### ISSUE THREAD

**Issue by michaelisvy** [prakhar1989/docker-curriculum#162]
Hi,
first of all thanks a lot for your tutorial! It's really well explained and answers many of the questions I had.

In the `Docker run`, section, we can see the following:
Danger Zone: If you're feeling particularly adventurous you can try rm -rf bin in the container. Make sure you run this command in the container and not in your laptop/desktop. Doing this will not make any other commands like ls, echo work. 

In my case, I could still use the command `echo` after removing the `bin` folder. However `ls` was not working anymore as indicated.

**Comment by prakhar1989** [comment]
My bad - `echo` is a shell built-in so it should still work. Fixed!

**Comment by michaelisvy** [comment]
thanks!
