### ISSUE TITLE
AWS Elastic Container Service - instructions do not work?

### ISSUE THREAD

**Issue by sjfke** [prakhar1989/docker-curriculum#163]
Trying to do this on Fedora28, so I create key-pair on EC2 interface, then

$ ecs-cli configure --region us-east-1 --cluster foodtrucks
INFO[0000] Saved ECS CLI cluster configuration default. 
$ ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro
FATA[0040] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors 

$ sudo dnf install awscli
$ sudo aws configure get region # returns none
$

Note: on EC2 Dashboard there is no 'us-east-1' zone.

I am trying to do this from France, not the US, but the EB instructions worked just fine? 
My notes are here: https://nonbleedingedge.com/howtos/docker-walkthrough.html

- Geoff

**Comment by sjfke** [comment]
I think the trouble starts here (see my notes link above):

$ gpg --version
$ sudo gpg --keyserver hkp://keys.gnupg.net --recv BCE9D9A42D51784F
gpg: requesting key 2D51784F from hkp server keys.gnupg.net
gpg: key 2D51784F: public key "Amazon ECS <ecs-security@amazon.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by piavgh** [comment]
I'm also stuck in the final step `AWS Elastic Container Service`

But the issue the I met is that I can't get pass this command line
`ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro`

I think the author should write it more carefully in this part:

> If you've not configured the AWS CLI on your computer before, you can use the official [guide](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-set-up.html) which explains everything in great detail on how to get everything going.

**Comment by Molakim** [comment]
I find a way to solve this problem, you just have to add your credentials with this command:

`ecs-cli configure profile --profile-name profile_name --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY`

To find your $AWS_ACCESS_KEY_ID and your $AWS_SECRET_ACCESS_KEY` follow these instructions that I found [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html):

1. Open the IAM console.
2. In the navigation pane of the console, choose Users.

3. Choose your IAM user name (not the check box).

4. Choose the Security credentials tab and then choose Create access key.

5. To see the new access key, choose Show. Your credentials will look something like this:

    * Access key ID: AKIAIOSFODNN7EXAMPLE

    * Secret access key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

6. To download the key pair, choose Download .csv file. Store the keys in a secure location.

Hope it can help

**Comment by junh-ki** [comment]
I am also stuck...

**Comment by prakhar1989** [comment]
Sorry, the instructions had become outdated since AWS changed some screens and configuration. However, i've updated that section as per the latest AWS setup and it should work. 

@junh-ki Can you please elaborate on what part you are stuck?
