### ISSUE TITLE
не работает docker rm $(docker ps -a -q -f status=exited)

### ISSUE THREAD

**Issue by Barcelonaglides** [prakhar1989/docker-curriculum#165]
$ docker rm $(docker ps -a -q -f status=exited)
unknown shorthand flag: 'a' in -a
See 'docker rm --help'.

=======
win-10
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by serlevki** [comment]
docker rm -v $(docker ps -aq -f status=exited)

**Comment by prakhar1989** [comment]
Thanks @serlevki for the fix =)
