### ISSUE TITLE
The "hello world" in Development Workflow part is not working as tutorial examples.

### ISSUE THREAD

**Issue by zhutianqi** [prakhar1989/docker-curriculum#166]
If we use the cloned code, the "grep hello app.py" command actually will show user modified code (In the tutorial example, it shows nothing).

I believe the reason is that yml file volume part actually mount "./flask-app:/opt/flask-app", and every time we grep, we are on user's app.py's layer.

**Comment by marcin-kulik** [comment]
I can confirm that the same happens to me.

    ```docker-compose run web bash
    Starting es ... done
    root@a92df1df49cb:/opt/flask-app# ls
    app.py  package-lock.json  package.json  requirements.txt  static  templates  webpack.config.js
    root@a92df1df49cb:/opt/flask-app# grep hello app.py
    # add a new hello route
    @app.route('/hello')
    def hello():
        return "hello world!"```

**Comment by tamakisquare** [comment]
I come here to report the same. Local change does get picked up by the container, which makes the following instruction in the tutorial unnecessary. 

> we need to tell docker compose to not use the image and instead use the files locally.

**Comment by mohamedrekik** [comment]
Same thing here! The changes took place in the file, but the URL doesn't work unless doing the supplementary steps.

**Comment by emiliodacosta** [comment]
Same thing here on March 25 of 2024
