### ISSUE TITLE
pip permission errors

### ISSUE THREAD

**Issue by rjpalermo1** [prakhar1989/docker-curriculum#17]
You can upgrade your instructions on flask-app to say if you get permission errors when running

`$ pip install -r requirements.txt`

and you don't want to sudo creating a global install of requirements.txt then use

`$ pip install --user -r requirements.txt`

ALSO you may want to tell dummy first timers like me to make sure and open their public port to 5000 if they are using a VPS...

**Comment by prakhar1989** [comment]
Thanks for pointing this out! I'll update the tutorial to indicate this.
