### ISSUE TITLE
busybox

### ISSUE THREAD

**Issue by dwctower** [prakhar1989/docker-curriculum#171]
Hi

Thank you for the tutorial. But unfortunately I couldn't pull the busybox so that could not carry on to follow the tutorial. Could you please help? I have googled and found someone faced the same problem but they solutions did help.
PS C:\> docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
no matching manifest for unknown in the manifest list entries

Thank you very much.

**Comment by prakhar1989** [comment]
Seems like you are on a windows box. I'm not sure what the issue - are you behind a proxy or something that's stopping you from the pulling images from hub.docker.com? If you are still stuck, I'd suggest trying on a different internet connection or spinning up a VM on a public cloud of your choice (AWS / GCP / Azure etc.) and going through a tutorial on that VM.
