### ISSUE TITLE
cmd doesn't work

### ISSUE THREAD

**Issue by tannertait** [prakhar1989/docker-curriculum#173]
$ docker run --rm prakhar1989/static-site

Unable to find image 'prakhar1989/static-site:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

I can't really move forward on this tutorial now, unfortunately.

**Comment by nicoladileo** [comment]
If you are using a VPN or you're connected under a firewall, please connect your machine direct to Internet and try again.

**Comment by prakhar1989** [comment]
As @nicoladileo suggests, this is a proxy / internet setup issue. Please try a different internet setup / remove proxy / VPN and try again.
