### ISSUE TITLE
Great tutorial - but cost me actual cash!

### ISSUE THREAD

**Issue by Jools69** [prakhar1989/docker-curriculum#174]
Very good tutorial, but it may be worth mentioning that if you leave your containerised app running on EC2, you will get charged for the AWS resources you use. I didn't realise until I got charged around $7 for almost a month's usage, and then after I thought I'd disabled the app, it was automatically spun up again, and I got charged another $12 the following month.

It's definitely all stopped now!

**Comment by alwell-kevin** [comment]
Now THATS High Availability 👍

**Comment by tartansandal** [comment]
Ouch. Just got stung by that too. It looks like simply deleting the clusters from the ECS console is not enough. I had to go to the EC2 console and delete the associated auto scaling groups.  I'm going to double check that that behaviour is repeatable and, if so, raise a ticket with AWS.

**Comment by tartansandal** [comment]
> Ouch. Just got stung by that too. It looks like simply deleting the clusters from the ECS console is not enough.

My  bad. There is a note in the 'Delete Cluster' dialog that explicitly says you have to delete all the associated CloudFormation resources yourself.  However, running:
```
ecs-cli down --force
```
does seem to take care of all that.

**Comment by prakhar1989** [comment]
Whoops, sorry about that folks. I've updated the tutorial with ways to cleanup.
