### ISSUE TITLE
Links to Docker Mac Installation are deprecated

### ISSUE THREAD

**Issue by alwell-kevin** [prakhar1989/docker-curriculum#176]
Link to provided [mac installation](https://www.docker.com/products/docker#/mac) is deprecated.

**Comment by tordbb** [comment]
The same goes for the windows installation: https://www.docker.com/products/docker-engine-old#/windows

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/commit/3389a8231d1f427f02b06ed82fc15b9876434c8d
