### ISSUE TITLE
Docker-curriculum AWS deployement problem.

### ISSUE THREAD

**Issue by him4research** [prakhar1989/docker-curriculum#178]

**Comment by him4research** [comment]
On deploying container on AWS elastic beanstalk, i am not able to understand which file to upload and how to upload a root file as i am working on root. can you please help me on that

**Comment by prakhar1989** [comment]
Just upload [this file](https://github.com/prakhar1989/docker-curriculum/blob/master/flask-app/Dockerrun.aws.json) as shown in [this screenshot](https://docker-curriculum.com/images/eb-docker.jpeg)
