### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by tordbb** [prakhar1989/docker-curriculum#179]
When a windows user calls 
     curl 0.0.0.0:9200 
in the terminal, there is an error message including "curl : Unable to connect to the remote server". 
After lots of googling, a colleague suggested it might be that this ip-adress does not work in windows. 
Instead, we tried
     curl 127.0.0.1:9200
and it finally worked. 
Perhaps you would like to update your splendid tutorial with this helpout for windows users?

Btw: I also can’t get the command 
              tree -L 2
to work. That is possibly also related to me using windows…

**Comment by ArtemSer** [comment]
`tree` is utility for "tree"-preview of your folders. This is not so important. With Windows you can check directories' content with `dir`

**Comment by prakhar1989** [comment]
As @ArtemSer mentioned, `tree` is just to view the contents of the directory. Using `dir` should be fine on Windows.

**Comment by AlexKalopsia** [comment]
I think what @tordbb was suggesting was to add this info to the tutorial since since the beginning it seems to be quite platform-agnostic. I spent a bunch of time finding answers to this.
