### ISSUE TITLE
Thank you! - Improvement Suggestions on Docker Tutorial 

### ISSUE THREAD

**Issue by Danelrf** [prakhar1989/docker-curriculum#180]
Thanks for the tutorial, it was a great way to get me started on the subject of docker without being too detailed or too abstract.

A couple things I noticed:
 - Grammar check on Section 'Docker Compose'
    _For each service**, that Docker needs to run,** we can add additional parameters out of which image is required. For es, we just refer to the elasticsearch image available on Elastic registry. For our Flask app, we refer to the image that we built at the beginning of this section._
  I believe the first comma is unnecessary.

- Regarding the use of "prakhar1989/xxxx"
Perhaps it would be good to write "yourusername/xxxx" instead of your specific one in the text, and optionally on the shown files, as this leads to some confusion to beginners, mostly because at some point it is necessary to pull from your actual 'repository'. 

Thank you so much again! You made it very interesting!

**Comment by prakhar1989** [comment]
Thanks for the feedback!
