### ISSUE TITLE
Google Trends chart goes back to 2005

### ISSUE THREAD

**Issue by mallove** [prakhar1989/docker-curriculum#181]
The [initial release of Docker was 2013](https://www.youtube.com/watch?v=wW9CAH9nSLs), but the [Google Trends image](https://github.com/prakhar1989/docker-curriculum/blob/master/tutorial/public/images/interest.png) shows mild interest in Docker in 2005.  I think the trends [time range and keyword search could be limited](https://trends.google.com/trends/explore?date=2012-05-27%202019-06-27&geo=US&q=docker%20software) to avoid ambiguous meaning of keyword `docker` (e.g., longshoreman).

**Comment by prakhar1989** [comment]
Good call - i'll go ahead and update the screenshot :)
