### ISSUE TITLE
A Docker Tutorial for beginners

### ISSUE THREAD

**Issue by luzi09** [prakhar1989/docker-curriculum#183]
The tutorial was very interesting and helpful - thanks a lot :-)

I skipped the AWS part...

The only issue was, that my curl ...5000/hello tells me:

curl 0.0.0.0:5000/hello
curl: (52) Empty reply from server

... and I don't know what was wrong or how to fix it

**Comment by lihao5257** [comment]
how about changing 0.0.0.0 to localhost?
Try it .

**Comment by prakhar1989** [comment]
Yup, if `0.0.0.0` doesn't work, try `localhost`.
