### ISSUE TITLE
Error docker build -t foodtrucks-web

### ISSUE THREAD

**Issue by dgroh** [prakhar1989/docker-curriculum#186]
I use docker for windows and I'm following the tutorial which has worked until now, but I'm not able to run `docker build -t myname/foodtrucks-web`

I get the following error:

>Step 1/13 : FROM ubuntu:latest
 ---> 3556258649b2
Step 2/13 : MAINTAINER Prakhar Srivastav <prakhar@prakhar.me>
 ---> Using cache
 ---> 3a31ad69ab3e
Step 3/13 : RUN apt-get -yqq update
 ---> Using cache
 ---> f4d65701e7a3
Step 4/13 : RUN apt-get -yqq install python-pip python-dev curl gnupg
 ---> Running in 674748da1ebf
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libk/libksba/libksba8_1.3.5-2_amd64.deb  Undetermined Error [IP: 91.189.88.24 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -yqq install python-pip python-dev curl gnupg' returned a non-zero code: 100

How can I solve this issue?

**Comment by edisoncks** [comment]
I am having similar issue when building docker image for foodtrucks-web.

```
Step 1/13 : FROM ubuntu:latest
 ---> 775349758637
Step 2/13 : LABEL maintainer="Prakhar Srivastav <prakhar@prakhar.me>"
 ---> Running in 3c16a6890b5a
Removing intermediate container 3c16a6890b5a
 ---> ce4caa7ec734
Step 3/13 : RUN apt-get -yqq update
 ---> Running in f07108614389
Removing intermediate container f07108614389
 ---> 69fdaa490f9e
Step 4/13 : RUN apt-get -yqq install python-pip python-dev curl gnupg
 ---> Running in 77c671c176e8
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/isl/libisl19_0.19-1_amd64.deb  Undetermined Error [IP: 91.189.88.149 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -yqq install python-pip python-dev curl gnupg' returned a non-zero code: 100
```

**Comment by prakhar1989** [comment]
Hi, i tried reproducing this issue but can't. [This](https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error) seems to suggest that it may be because you are behind a proxy. Try adding 

```
RUN apt-get clean
```

before `apt-get update` in the `Dockerfile` and see if it solves the issue.
