### ISSUE TITLE
Folder

### ISSUE THREAD

**Issue by sachinnair8** [prakhar1989/docker-curriculum#188]
Why can't I see catnip folder similar to how I can see static-site folder here?

I requested pull for catnip and it worked. But I am not sure where it pulled from. Newbie to Docker, so sorry if it sounds like naive question.

**Comment by prakhar1989** [comment]
I think by folder you are referring to a docker image in which case until you pull an image, you won't be able to see it locally. 

Feel free to reopen the issue if that answer your question.
