### ISSUE TITLE
Repository does not exist 

### ISSUE THREAD

**Issue by sorcererstone** [prakhar1989/docker-curriculum#190]
Hello Prakhar,
I ran into a problem when I attempted to run the command in Dockerfile section. I built the catnip successfully. 
But when I issued the command "docker run -p 8888:5000 sorcerer/catnip", I received an error saying it is either a docker login denial or the repository does not exit. See attached screenshots.
![flaskDirectory](https://user-images.githubusercontent.com/16738737/63288147-0663f400-c28a-11e9-868b-1a8ed6d6033a.jpg)
![CatnipAccessDenial](https://user-images.githubusercontent.com/16738737/63288148-06fc8a80-c28a-11e9-8050-0948af844427.jpg)

My OS is Win10pro but with Hyper-V disabled. To run container, I am using the latest Virtualbox and the latest Docker Toolbox. I am running the above command from the flask-app folder.

I have looked at the similar errors for this project, but my error is different from what were reported earlier.
Please advise.

**Comment by Ichimonji10** [comment]
`docker build -t prakhar1989/catnip .` builds an image and gives it a tag of `prakhar1989/catnip`. Then, `docker run -p 8888:5000 sorcerer/catnip` tells dockerd to spin up a container from the `sorcerer/catnip` image. See the problem? The first command references the tag `prakhar1989/catnip`, and the second references the tag `sorcerer/catnip`.

**Comment by prakhar1989** [comment]
Yup, @Ichimonji10 is correct, both images are different. Just use the same image name when building and running, and it should work.
