### ISSUE TITLE
FoodTrucks-Web not showing any trucks

### ISSUE THREAD

**Issue by DukeVimes** [prakhar1989/docker-curriculum#196]
Followed the tutorial on Windows 10 Home using docker-toolbox.
Elastic-search is starting and can be reached with curl.
The json-file elastic-search should be parsing is accessible.
The foodtrucks-web container is running and connects to es, and displays the website.

There is just not a single truck visible on the map.
During startup the web-container displays directly "* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)"

There is no mention of

"Index not found...
Loading data in elasticsearch ...
Total trucks loaded:  733"

**Comment by tartansandal** [comment]
Hi @DukeVimes. There is a small bug in the web-app that prevents the truck locations from being displayed. Checkout the PR at https://github.com/prakhar1989/FoodTrucks/pull/20 for a one-line patch.

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/FoodTrucks/commit/ec749b2017a9c3f8a869f24b0ae0aaa9a6980284
