### ISSUE TITLE
docker-compose: can't open file './app.py'

### ISSUE THREAD

**Issue by DukeVimes** [prakhar1989/docker-curriculum#197]
MINGW64 /c/projects/FoodTrucks (master)
$ docker-compose up

Creating network "foodtrucks_default" with the default driver
Creating es ... done
Creating foodtrucks_web_1 ... done
Attaching to es, foodtrucks_web_1
web_1  | python: can't open file './app.py': [Errno 2] No such file or directory
foodtrucks_web_1 exited with code 2

without compose I can run the container just fine, and there is a the app.py in the working directory.

**Comment by ctriou** [comment]
I'm having the same issue. Currently I'm running docker inside WSL with `export DOCKER_HOST=localhost:2375` as part of my `.bash_profile`

**Comment by ctriou** [comment]
Nevermind actually, turns out there's some issues with Docker volumes being mapped in WSL by default. `docker-compose up` works fine with your example in my Windows environment.

**Comment by mainstringargs** [comment]
I had the same issue.  I was able to get it to work on CentOS 7 by appending ":z" to the end of the volumes.  I think this fixes the permissions problems with the container.

So:

```
volumes:
  - ./flask-app:/opt/flask-app:z
```
