### ISSUE TITLE
Getting Error while creating elastic search container

### ISSUE THREAD

**Issue by sarvjeetrajvansh** [prakhar1989/docker-curriculum#199]
$ docker pull elasticsearch:6.8.3
6.8.3: Pulling from library/elasticsearch
d8d02d457314: Already exists
bb60ada87aba: Extracting [==================================================>] 198.6 MB/198.6 MB
b0aa5c8ae12e: Download complete
12ff10d2e79f: Download complete
126f27fca7c7: Download complete
6eed0668b9a4: Download complete
dc915c0e5cf6: Download complete
failed to register layer: devmapper: Unknown filesystem type on /dev/mapper/docker-8:2-2235229-1d527e83473aef3c0d2d72d3538c60bb01c2a8baad78fc1adc5438a0a5003605

**Comment by prakhar1989** [comment]
Hi, can you please share which docker version and OS are you on? Also the image for elastic search is diff - please check the tutorial for the updated instructions.

**Comment by sarvjeetrajvansh** [comment]
It's been too long, I was working on this.
Thanks for your response.

Closing the issue.
