### ISSUE TITLE
Need to setup profile

### ISSUE THREAD

**Issue by msmaromi** [prakhar1989/docker-curriculum#203]
Before I ran this command:
`ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro`
I need to configure profile with access key & access secret key first:
`ecs-cli configure profile --profile-name profile_name --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY`

**Comment by prakhar1989** [comment]
Yup, sorry for missing out on that part before. The ECS section has been updated with that command.
