### ISSUE TITLE
$ docker rm $(docker ps -a -q -f status=exited) errors

### ISSUE THREAD

**Issue by ndunn219** [prakhar1989/docker-curriculum#205]
The following command errors on version 19.03.2, build 6a30dfc

$ docker rm $(docker ps -a -q -f status=exited)

The error I get is:
unknown shorthand flag: 'a' in -a

"docker container prune" works fine

**Comment by prakhar1989** [comment]
Weird.. I'm on the same version and the command works fine for me. As per the [documentation](https://docs.docker.com/engine/reference/commandline/ps/), `-a` command should work fine as well. 
 
<img width="572" alt="Screen Shot 2020-04-12 at 12 28 59 PM" src="https://user-images.githubusercontent.com/649249/79077873-45cbce80-7cb9-11ea-86f5-78173e2ab57b.png">


I'm glad `docker container prune` worked for you though.
