### ISSUE TITLE
When setting up the CloudFormation -- Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated

### ISSUE THREAD

**Issue by rp779** [prakhar1989/docker-curriculum#206]
When trying to enable to ecs-CLI to create a CloudFormation template the command used:
```ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro``` 

produced the following error:
```ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro
FATA[0005] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors```

Up until this point everything had been working. I made sure that I properly identified my keypair as well as my region in the previous commands. I checked my ECS console and made sure that the everything was working. My only thought is that this is a result of an updated ecs-cli configuration since the time of your article.

**Comment by nsp54058** [comment]
same issue for me

**Comment by joereg4** [comment]
I ran into the same issue and resolved it basically in two steps after following Amazon's walkthrough of setting up [ECS CLI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html):

1. Creating Access Keys
2. Configuring AWS on the local machine

Once installed I went to 'My Security Credentials' in AWS and created Access Keys.  In the terminal on I ran `Mac-Pro: joe$ aws2 configure` which prompts for the Access Key ID and then the Private Key which was contained in a CSV downloaded as part of the access key creation.  The installation instructions include a different command `ecs-cli configure profile --profile-name profile_name --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY` where you can substitute your information with the desired items but I didn't use it. 

It also asks for the Region and output of the [configuration files](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_Configuration.html).

I then ran the `ecs-cli up --keypair ecs --capability-iam --size 2 --instance-type t2.micro` and it worked.

**Comment by technoplato** [comment]
I don't know if the ECS CLI docs have changed, but this looks like the correct link to configure the CLI: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_Configuration.html

**Comment by prakhar1989** [comment]
Just added some instructions on clarifying this bit. Feel free to reopen if its causes confusion.

**Comment by technoplato** [comment]
Excellent, thank you for this guide its invaluable to getting started.
