### ISSUE TITLE
Docker studying never works for a web site

### ISSUE THREAD

**Issue by swimhiking** [prakhar1989/docker-curriculum#208]
Hi There,

Not sure what issue it is , I tried follow the tutorial (https://docker-curriculum.com/) almost one week to try run this test ( docker-curriculum/flask-app), never works, very frustrated tested with 2 Windows 10 pro PC, docker version 19.03.4.

- it display build and run success;

- I inspect the container ID, get IP address, browser never works

- docker container ls show status running

- using Kitematic show 404.

- DockerNAT set to external network

Could you help me with this? Thanks

**Comment by prakhar1989** [comment]
Can you tell me which command you are trying to run?
