### ISSUE TITLE
Warning after docker pull

### ISSUE THREAD

**Issue by Heaven31415** [prakhar1989/docker-curriculum#209]
Hey, when I tried to pull `prakhar1989/static-site` image I got the following warning:

> Image docker.io/prakhar1989/static-site:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/

**Comment by prakhar1989** [comment]
Thanks for creating the issue! Just did a `push` again, and this should be fixed.
