### ISSUE TITLE
Not prompted to login on docker push

### ISSUE THREAD

**Issue by AlexKalopsia** [prakhar1989/docker-curriculum#217]
Hi and thanks for the curriculum. So far I have only found a small issue, on the Push section (https://docker-curriculum.com/#docker-on-aws). 

The tutorial suggests that if it's the first time pushing, the console will ask for credentials. This was not the case for me, I just got a permission error. So I started looking around checking how to fix this, and yes, it turns out I can just do `docker login` first. 

After doing that, I went back in the tutorial and realized that the following lines did use `docker login`. So I think it's a matter of changing "the client will ask you to login" to "you should first provide the login credetials with `docker login`

**Comment by prakhar1989** [comment]
This has been fixed in #237. Thanks for the bug.
