### ISSUE TITLE
Authentication for public repos -- nonsensical?  CannotPullContainerError

### ISSUE THREAD

**Issue by carlcrott** [prakhar1989/docker-curriculum#218]
Nearing the end of the tutorial (https://docker-curriculum.com/#aws-elastic-container-service) and Im attempting to run the final deploy to ECS.

my aws-compose.yml
```
  image: elasticsearch
```
Running the final command to deploy:

`$ ecs-cli compose --file aws-compose.yml up`

Error:

> ... STOPPED Reason: CannotPullContainerError: Error response from daemon: manifest for elasticsearch:latest not found

with a modified aws-compose.yml:

```
  image: elasticsearch/elasticsearch:6.3.5
```

`$ ecs-cli compose --file aws-compose.yml up`
Error:

> ... STOPPED Reason: CannotPullContainerError: Error response from daemon: pull access denied for elasticsearch/elasticsearch, repository does not exist or may require 'docker login'

Is this correct?  A **public** repo requires authentication for ECS?

**Comment by carlcrott** [comment]
Currently I believe this could be 2 possible problems:

1) ecs-cli requires that I be authenticated to access a public (elastisearch) repo.
2) A problem with network access for ECS ( network permissions to access public internet )

**Comment by prakhar1989** [comment]
`elasticsearch/elasticsearch:6.3.5` is not a valid image.. its actually `docker.elastic.co/elasticsearch/elasticsearch:6.3.5` as referenced in the official ElasticSearch docs - https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

You are right in assuming that pulling public images do not require login.
