### ISSUE TITLE
Flask-app / Статья на hubr про Docker & AWS 2016 года

### ISSUE THREAD

**Issue by Aranhaely** [prakhar1989/docker-curriculum#219]
Добрый день или вечер!
Прочитал Вашу статью, было интересно, спасибо! Но...
Всё бы хорошо, но Dockerfile в примере с ES + Flask (глава 3-4) на данный момент описан с ошибками!
1. "... Run apt-get -yqq update
     Run apt-get -yqq install ... "
Требует установки **apt-utils** в контейнере! Ему не нравиться параметр диалога **-qq**.
2. `Add flask-app /opt/flask-app` с ошибкой -> должно быть `Add /flask-app /opt/flask-app` А сам Dockerfile необходимо вынести из папки flask-app иначе не работало.
3. `Run npm . . .` выдаёт масс ошибки. Часть решается переносом файла package.json в корень flask-app, но не все.
(Ну и про слои ничего не сказано, предложены массовые инструкции Run по умолчанию)
Не знаю, запускал ли кто Ваш код, но в комментах информации о таком что то не нашел за несколько часов безуспешных фиксов. Надеюсь Вы поправите! 
Спасибо за труд!
(фикшеный мной Dockerfile Вашего туториала)
[Dockerfile.zip](https://github.com/prakhar1989/docker-curriculum/files/4083668/Dockerfile.zip)

**Comment by prakhar1989** [comment]
1. The default version of ubuntu, should have `apt-get` already installed so it doesn't need to be installed 

2. > А сам Dockerfile необходимо вынести из папки flask-app иначе не работало.

Not sure what you mean by this

3. You don't need to run each step individually, just add them to the Dockerfile. 

Sorry, but I'm having a hard time understanding this bug.. can you run `docker build -t .` and share the output?
