### ISSUE TITLE
Getting error while runing docker build command in multicontainer workshop

### ISSUE THREAD

**Issue by sa867b** [prakhar1989/docker-curriculum#220]
[root@kubmaster FoodTrucks]# docker build -t sa867b/foodtrucks-web .
Sending build context to Docker daemon  6.737MB
Step 1/13 : FROM ubuntu:latest
 ---> ccc6e87d482b
Step 2/13 : LABEL maintainer="Prakhar Srivastav <prakhar@prakhar.me>"
 ---> Using cache
 ---> 0e5f7304a6a0
Step 3/13 : RUN apt-get -yqq update
 ---> Running in 13b76c6b54c0
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 1d 2h 57min 51s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1d 2h 58min 42s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 1d 2h 59min 56s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get -yqq update' returned a non-zero code: 100

**Comment by prakhar1989** [comment]
Hmm, seems like a temporary issue with the ubuntu repos. Can you try again and see if it works?
