### ISSUE TITLE
grammar

### ISSUE THREAD

**Issue by kingrhoton** [prakhar1989/docker-curriculum#221]
"The --rm is a convenient flag for running one off commands since the container gets cleaned up when it's work is done."

This should be "its".   Otherwise, congratulations on one of the best tutorials I've seen in years.  Everything worked, you explained almost all the code, and you anticipated almost all of my questions!  Thanks!

**Comment by prakhar1989** [comment]
Thank you!

**Comment by prakhar1989** [comment]
Fixed
