### ISSUE TITLE
Error with Docker tutorial

### ISSUE THREAD

**Issue by savvasd** [prakhar1989/docker-curriculum#222]
Hi there

I've followed the docker tutorial (word for word I think!)
But when the time comes to run the catnip container, I cannot see the site, I am getting a "This site can't be reached" error page 
I have tried 0.0.0.0:8000
0.0.0.0:5000
and the IP in the pic 192.168,something, with both ports... no luck
Any ideas?

**Comment by kent-hervey** [comment]
Me, too.  I am looking to see if others asked this question.

**Comment by kent-hervey** [comment]
both localhost and 0.0.0.0 worked for me

**Comment by prakhar1989** [comment]
Ya, both `localhost` and `0.0.0.0` work.. it might take a few seconds for it to pick up though. I should update that pic as that ip address is misleading.

**Comment by prakhar1989** [comment]
Updated the screenshots for the catnip app to show localhost in URL. Hopefully that doesn't confuse readers anymore.
