### ISSUE TITLE
Ubuntu ...localhost works, but 192.168.99.100 does not....

### ISSUE THREAD

**Issue by kent-hervey** [prakhar1989/docker-curriculum#223]
Tutorial says:
The command we just ran used port 5000 for the server inside the container and exposed this externally on port 8888. Head over to the URL with port 8888, where your app should be live.

Then shows a picture using:  192.168.99.100:8888

However, that did not work...timed out

I Googled wondering about using localhost, but results say that won't work

I came here and somebody said it would and it did..

Maybe change the tutorial?

**Comment by meatnordrink** [comment]
> Tutorial says:
> The command we just ran used port 5000 for the server inside the container and exposed this externally on port 8888. Head over to the URL with port 8888, where your app should be live.
> 
> Then shows a picture using: 192.168.99.100:8888
> 
> However, that did not work...timed out
> 
> I Googled wondering about using localhost, but results say that won't work
> 
> I came here and somebody said it would and it did..
> 
> Maybe change the tutorial?

Hey @kent-hervey , that is a little confusing - what the picture is showing is the author's local ip address, which is the same as `localhost` *for him.* Your ip address will be different than his, of course.

**Comment by kent-hervey** [comment]
Thanks

**Comment by Hakeemmidan** [comment]
Yes, I had the same issue and on meatnordrink's point above, going to `http://localhost:8888` should solve it

**Comment by prakhar1989** [comment]
Thanks @meatnordrink !
