### ISSUE TITLE
docker run --rm prakhar1989/static-site -bash: $: command not found

### ISSUE THREAD

**Issue by cawahe** [prakhar1989/docker-curriculum#224]
docker run --rm prakhar1989/static-site
-bash: $: command not found

i can't get the webpage to work.

**Comment by meatnordrink** [comment]
@cawahe It looks like maybe you entered the `$` when you tried the command? 

You don't actually enter the `$`; that's just a traditional convention for showing the bash command line.

**Comment by prakhar1989** [comment]
Thanks @meatnordrink for clarifying. @cawahe: I'm closing out the issue but feel free to re-open if the issue resurfaces.
