### ISSUE TITLE
Short list of potential clarity improvements

### ISSUE THREAD

**Issue by meatnordrink** [prakhar1989/docker-curriculum#228]
Wonderful tutorial, so helpful!!! Many thanks. I realize things that seem confusing to those reading are usually obvious to those writing; I offer these acknowledging this and in the spirit of improving it for those to come!

* It would be great to say explicitly what the flags are doing, and the syntax the commands take. For example: 
  * It's confusing why the first `COPY` command in the dockfile is `COPY . .`, and unexplained. 
  * It's not really clear that the `-t` is the flag that allows us to name the image with our username/image combo: `docker build -t yourusername/catnip .`
  * Though a full explanation is too advanced for the tutorial, some simple explanation for the `-e` flag here would be nice: `docker run -d --name es -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.3.2`
* It's also a little confusing that you move from using `localhost` to an explicit ip address in the picture below this line: "Head over to the URL with port 8888, where your app should be live." Though I suppose anyone learning docker should probably recognize what's going on, I suppose.
* I think it could be clearer that you're pulling from the Elastic registry rather than Docker Hub, here, as you searched the Docker Hub; it's a bit confusing why the pull doesn't match what we saw in the search. 

Again, thank you so much. I've tried to answer a few of the simpler questions on here, to compensate for my adding another one. :)

(Also, I'm happy to pull and edit these myself, but I wasn't sure if that's customary for this repo.)

**Comment by prakhar1989** [comment]
Great suggestions - thank you! I'll get to these as soon as I get a chance. Thank you so much for leaving feedback!
