### ISSUE TITLE
Can't find option -it in Help

### ISSUE THREAD

**Issue by ilyasDevGit** [prakhar1989/docker-curriculum#234]
Hi all,

I'm study Docker. 
I cannot find option "-it" in listing after running Docker run --help!?

Why is that?

Br, ilyas

**Comment by prakhar1989** [comment]
These are two separate flags - `-i` and `-t` for which you will be able to find documentation via the help command. In most cases, you can merge Unix command flags into one as demonstrated in the tutorial.
