### ISSUE TITLE
Slight confusion on building image under section 2.4

### ISSUE THREAD

**Issue by televators** [prakhar1989/docker-curriculum#24]
This is my first time learning and using docker and your tutorial is great. I did have a problem because of the way the tutorial is laid out and your choice of text placement. Under section 2.4 at, "Let's run the following (don't forget the period!) -", you say to use the following command which is in a large pre-tag box and only after that do you specify that we should use our user name instead of yours. I didn't realize that that is how it is being associated with your repo and I can't find a simple way to change the associated user for the image I created. Anyone who already knows what's going on would know already that that is where their user name goes but a newby literally doing exactly as you say in order, like me, is going per line. So, after I created the image and then scrolled down to be able to see the following paragraph, I found out I'm stuck on your repo.

**Comment by prakhar1989** [comment]
Hi @televators - Thanks for opening the issue. I'm sorry you got confused by the tutorial. I agree that the placement of that line should be above, and I'll surely make that change. 

Btw, if you're still stuck on how to change the image name, here's how you can do that 

1. Get the image ID. Use `docker images` for that - 

```shell
$ docker images
REPOSITORY                              TAG                 IMAGE ID             CREATED             SIZE
prakhar1989/nodimg                     latest              c272ee0b6503        2 days ago          1.457 GB
```

The ID of the image is `c272ee0b6503`.

2. We can now change the name of the image by the following command - 

```
$ docker tag c272ee0b6503 televators/flask_image:latest
```

Let me know if you're still stuck.

Best,

**Comment by televators** [comment]
Thanks! I just deleted the image and remade it properly so all is well. Thank you for the tip, I'll add that to my notes. Thanks for the lightning fast response as well! Have a great day.

[Nanoshrine Studios LLC Logo] [http://bit.ly/6psP0I]

Justin Higgs [mailto:justin@nanoshrine.com] - President
Nanoshrine Studios LLC [http://www.nanoshrine.com] - 850.284.3077 [tel:8502843077]
On 6/13/2016 9:35:40 PM, Prakhar Srivastav <notifications@github.com> wrote:
Hi @televators [https://github.com/televators] - Thanks for opening the issue. I'm sorry you got confused by the tutorial. I agree that the placement of that line should be above, and I'll surely make that change.
Btw, if you're still stuck on how to change the image name, here's how you can do that
* Get the image ID. Use docker images for that -
$ docker images REPOSITORY TAG IMAGE ID CREATED SIZE prakhar1989/nodimg latest c272ee0b6503 2 days ago 1.457 GB
The ID of the image is c272ee0b6503.
* We can now change the name of the image by the following command -
$ docker tag c272ee0b6503 televators/flask_image:latest
Let me know if you're still stuck.
Best,
