### ISSUE TITLE
foodtrucks - can't connect to 0.0.0.0 from host computer to es container

### ISSUE THREAD

**Issue by natalyrudni** [prakhar1989/docker-curriculum#242]
Thanks a lot for the great tutorial!

I'm experiencing a problem from the  host computer to the container with the ip 0.0.0.0.
I'm using a Win10 host and Docker desktop version 2.2.0.5.

connecting to the es container and running curl localhost9200 works well
connecting from the flask-app to the es:9200 after creating the network between them also works
but the connection to 0.0.0.0 from outside of the container returns the following error:

PS C:\Users\natalyr> curl 0.0.0.0:9200
curl : Unable to connect to the remote server

tried to use the following suggested solution but the command failed to run:
https://mad.is/2016/09/running-elasticsearch-in-docker-container/

Elasticsearch suggests to update elasticssearch.yml, not sure where this file exist if I'm, using a Docker image.

Any idea?

**Comment by prakhar1989** [comment]
Are you able to correctly access [static-site](https://docker-curriculum.com/#static-sites) and the [flask-app](https://docker-curriculum.com/#our-first-image)? I'm wondering if port forwarding is not working for some reason or is there some other issue.

**Comment by natalyrudni** [comment]
Yes, I'm able to connect to  static-site
<https://docker-curriculum.com/#static-sites> and the flask-app
<https://docker-curriculum.com/#our-first-image>, only  foodtrucks doesn't
seem to work.

**Comment by prakhar1989** [comment]
Can you try running `docker-compose ps` and `docker-compose logs` and paste that info here? Might provide some hints as to what's wrong. Also I'm sure you've tried this but can you also give `localhost:9200` a shot and see if that succeeds?
