### ISSUE TITLE
cannot build foodtrucks app - pulled ubuntu 20.04

### ISSUE THREAD

**Issue by beH3uH** [prakhar1989/docker-curriculum#244]
Cannot build the foodtrucks because the Dockerfile specified latest build, which pulled 20.04.
My wokaround was to pull image ubuntu:18.04

[root@localhost FoodTrucks]# docker build -t ivalchev1/foodtrucks-web .
Sending build context to Docker daemon  9.511MB
Step 1/13 : FROM ubuntu:latest
latest: Pulling from library/ubuntu
d51af753c3d3: Pull complete
fc878cd0a91c: Pull complete
6154df8ff988: Pull complete
fee5db0ff82f: Pull complete
Digest: sha256:747d2dbbaaee995098c9792d99bd333c6783ce56150d1b11e333bbceed5c54d7
Status: Downloaded newer image for ubuntu:latest
 ---> 1d622ef86b13
Step 2/13 : LABEL maintainer="Prakhar Srivastav <prakhar@prakhar.me>"
 ---> Running in f977b23f2490
Removing intermediate container f977b23f2490
 ---> 30134c1edb53
Step 3/13 : RUN apt-get -yqq update
 ---> Running in c54fcd4fdc5c
Removing intermediate container c54fcd4fdc5c
 ---> 0acbf74d9ac9
Step 4/13 : RUN apt-get -yqq install python-pip python-dev curl gnupg
 ---> Running in 0807e26b1b70
E: Unable to locate package python-pip
The command '/bin/sh -c apt-get -yqq install python-pip python-dev curl gnupg' returned a non-zero code: 100

**Comment by beH3uH** [comment]
It stopped at the step to install pip.

I tried modifying the image to be able to properly use pip3, but gave up halfway through because it could lead to other implications.

**Comment by BethKnight1234** [comment]
I changed the version to 
`FROM ubuntu:14.04 `
and it's working. Also haven't finished tutorial so not sure if this hack will work for rest of it.

**Comment by moorekwon** [comment]
It seems some sintax errors occur in the app.py when executing docker run in another version of ubuntu.
