### ISSUE TITLE
Can I post it in Korean on my devblog?

### ISSUE THREAD

**Issue by moorekwon** [prakhar1989/docker-curriculum#248]
Hello, I was searching for good docker docs to study, and found this good tutorial.
It was very helpful for me to understand docker, and I would like to post it in Korean on my individual blog.
Is it possible?

**Comment by prakhar1989** [comment]
You can share the korean version with me, and I can host it on this site as well (while citing credits to you of course). Feel free to send a PR and we can take it forward from there.

Closing this for now.
