### ISSUE TITLE
Can only see static-site at custom port

### ISSUE THREAD

**Issue by Piyush3dB** [prakhar1989/docker-curriculum#25]
Hello,

I'm running ubuntu and I've done the following:

``` bash
piyush@fulmar:~$ docker run -d -P --name static-site prakhar1989/static-site
f24c9271a2b66b353c779aba0c52ba088cd39af210e65d66f1e77f0425906863
piyush@fulmar:~$ docker port static-site
443/tcp -> 0.0.0.0:32768
80/tcp -> 0.0.0.0:32769
```

When I go to http://localhost:32768 I can't see anything, but if I do the following

``` bash
piyush@fulmar:~$ docker run -p 8888:80 prakhar1989/static-site
```

Then http://localhost:8888 works.  Why is this happening?

Thanks for the great tutorial!

**Comment by prakhar1989** [comment]
Did you try running `docker-machine ip default` after the first command? It might be the case that it is not bound to `localhost`. If that is indeed the case, I'll need to update the tutorial so as to not mis-guide folks. 

Do let me know if that works for you. Although the surprising part is that the second scenario works.

**Comment by budkin** [comment]
I can't see the website neither on a random port, nor on a defined one. The page keeps loading indefinitely. Also I don't have the `docker-machine` command

**Comment by budkin** [comment]
Okay, I figured it out, `docker-machine` is a separate package. I run `docker-machine ip default` and it gives me
>Host does not exist: "default"

**Comment by prakhar1989** [comment]
@budkin does the following work -

```
$ docker-machine rm default
$ docker-machine create --driver virtualbox default
```
