### ISSUE TITLE
[BUG] Unable to bring the container up with ecs-utils: logging error.

### ISSUE THREAD

**Issue by fergycool** [prakhar1989/docker-curriculum#253]
I’m a complete newbie with both Docker and AWS. However, I did come across a possible issue towards the end of the tutorial.

Running the following always gave me an error about being unable to create the logging group:

`ecs-cli compose up`

>  STOPPED Reason: CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: ResourceNotFoundException: The specified log group does not exist.

`ecs-cli ps`showed all containers were stopped.

After consulting with the Amazon “ecs-client” tutorial* I instead used the following command:

`ecs-cli compose up --create-log-groups --cluster-config foodtrucks --ecs-profile ferg`

This did work, although I got a warning that the specified log group did now exist.

However, the Foodtrucks app did work on the resulting AWS IP address.

Thanks for the tutorial. Keeping my lockdown interesting!

*[ECS CLI Tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-ec2.html)

**Comment by valerii-vorobiov** [comment]
Had the same problem
Running 
`ecs-cli compose up --create-log-groups` helped me, even I had a warning "The specified log group already exists"
