### ISSUE TITLE
Problem with your tutorial

### ISSUE THREAD

**Issue by fili8848** [prakhar1989/docker-curriculum#254]
Hi there,

Just want to let you know that I've invested about 7 hours battling with your tutorial, helped by a colleague who knows quite a bit about docker, and we have been unable to get the elasticsearch container working properly. We get an empty reply from server. We have tried with masses of memory, 8Gb, the Java tweaks, and everything we can think of, but nothing has worked. We have also tried with version 6.8.9 of elasticsearch. A shame, because the tutorial is cool, so I hope you can update it.

**Comment by prakhar1989** [comment]
Hi, sorry that you ran into an issue with the tutorial.  I tried out the foodtrucks app, just now and it works for me. Did you try pulling in the latest changes in foodtrucks repo? https://github.com/prakhar1989/FoodTrucks

Basically, I just did 

```
git clone https://github.com/prakhar1989/FoodTrucks
cd Foodtrucks
docker-compose up
```

Can you run these commands and paste the output?

**Comment by fili8848** [comment]
Hi Prakhar, thanks for the reply. Yes, those three commands are exactly
what I was doing.
The situation is that I'm very tight with time. Knowing that it did work
for you, what I will do is create a new virtual machine from scratch and
try again. It will take me time to find a window to do it, but I'll keep
you posted.
Cheers

**Comment by prakhar1989** [comment]
Sounds good, thanks @fili8848
