### ISSUE TITLE
Read timeout docker build  foodtrucks-web

### ISSUE THREAD

**Issue by pnatusch** [prakhar1989/docker-curriculum#255]
The ping time to pypi.python.org was very slow 2. 8 ms+
How can I increase the read timeout?

/FoodTrucks @us122.sjc> docker build -t pnatuch4/foodtrucks-web .
Sending build context to Docker daemon  9.522MB
Step 1/13 : FROM ubuntu:18.04
Step 11/13 : RUN pip3 install -r requirements.txt
 ---> Running in ce2825ca8964
Collecting certifi==2020.4.5.1 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after \
connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection o\
bject at 0x7f6b48798978>, 'Connection to pypi.python.org timed out. (connect timeout=15\
)')': /simple/certifi/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after \
connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', por\
t=443): Read timed out. (read timeout=15)",)': /simple/certifi/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after \
connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', por\
t=443): Read timed out. (read timeout=15)",)': /simple/certifi/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after \
connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection o\
bject at 0x7f6b48790be0>, 'Connection to pypi.python.org timed out. (connect timeout=15\
)')': /simple/certifi/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after \
connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection o\
bject at 0x7f6b48790208>, 'Connection to pypi.python.org timed out. (connect timeout=15\
)')': /simple/certifi/
  Could not find a version that satisfies the requirement certifi==2020.4.5.1 (from -r \
requirements.txt (line 1)) (from versions: )
No matching distribution found for certifi==2020.4.5.1 (from -r requirements.txt (line \
1))
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

**Comment by prakhar1989** [comment]
Seems like an issue with your internet / network setup. Are you behind a proxy or something? Are you getting the same error multiple times?

**Comment by pnatusch** [comment]
All set I used a mirror
