### ISSUE TITLE
[BUG] ElasticSearch is stuck at license [4a90de77-97d9-4e5a-8d68-a47a4157a45f] mode [basic] - valid

### ISSUE THREAD

**Issue by mpfdj** [prakhar1989/docker-curriculum#258]
Let me start by saying your tutorial is great!

But unfortunately when running docker-compose up from ./Foodtrucks folder. I see ElasticSearch is stuck at license [4a90de77-97d9-4e5a-8d68-a47a4157a45f] mode [basic] - valid. How can I fix this?

I'm using image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0

Below you can see the log from ElasticSearch container.

"docker-cluster", "node.name": "6b7fbdeb7bb0", "message": "adding index lifecycle policy [watch-history-ilm-policy]", "cluster.uuid": "p445sBYZQWKiKi6FaM7abA", "node.id": "xWY7KqgmREGdP0xWavXXmA"  }
es     | {"type": "server", "timestamp": "2020-06-02T18:18:35,855Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "6b7fbdeb7bb0", "message": "adding index lifecycle policy [ml-size-based-ilm-policy]", "cluster.uuid": "p445sBYZQWKiKi6FaM7abA", "node.id": "xWY7KqgmREGdP0xWavXXmA"  }
es     | {"type": "server", "timestamp": "2020-06-02T18:18:35,953Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "6b7fbdeb7bb0", "message": "adding index lifecycle policy [slm-history-ilm-policy]", "cluster.uuid": "p445sBYZQWKiKi6FaM7abA", "node.id": "xWY7KqgmREGdP0xWavXXmA"  }
es     | {"type": "server", "timestamp": "2020-06-02T18:18:36,066Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "6b7fbdeb7bb0", "message": "adding index lifecycle policy [ilm-history-ilm-policy]", "cluster.uuid": "p445sBYZQWKiKi6FaM7abA", "node.id": "xWY7KqgmREGdP0xWavXXmA"  }
es     | {"type": "server", "timestamp": "2020-06-02T18:18:36,449Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "6b7fbdeb7bb0", "message": "license [4a90de77-97d9-4e5a-8d68-a47a4157a45f] mode [basic] - valid", "cluster.uuid": "p445sBYZQWKiKi6FaM7abA", "node.id": "xWY7KqgmREGdP0xWavXXmA"  }

**Comment by chpoullet** [comment]
I am getting the same issue. After showing the LicenseService it follows with:

web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Out of retries. Bailing out...
foodtrucks_web_1 exited with code 1


This is happening when running 'docker-compose up'.

**Comment by jeroenhendricksen** [comment]
Maybe you can use the oss (Open Source Software) version of elasticsearch? This version should be feature rich enough for the served purpose and avoid any license hassle.

Just replace `docker.elastic.co/elasticsearch/elasticsearch:7.7.0` with `docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0`.

**Comment by mpfdj** [comment]
I solved the problem by increasing the timeout to 15 seconds (time.sleep(15)). You have to update the following file: Foodtrucks/flask-app/app.py.

Looks like elasticsearch was not fully up and running when the web container is being started (even though is defined as a dependency in the docker-compose.yml file)



def safe_check_index(index, retry=3):
    """ connect to ES with retry """
    if not retry:
        print("Out of retries. Bailing out...")
        sys.exit(1)
    try:
        status = es.indices.exists(index)
        return status
    except exceptions.ConnectionError as e:
        print("Unable to connect to ES. Retrying in 5 secs...")
==> time.sleep(15)
        safe_check_index(index, retry-1)
