### ISSUE TITLE
Import Error on 'python app.py'

### ISSUE THREAD

**Issue by aaronwbrown** [prakhar1989/docker-curriculum#26]
I get an error when attempting to launch the flask app. It could have something to do with the way my Python is configured, but I wanted to see if anyone else was running into this problem, or had a clean way to resolve it. I am not too familiar with Python/Flask.

<img width="638" alt="screen shot 2016-06-18 at 12 20 16 pm" src="https://cloud.githubusercontent.com/assets/3529206/16173212/f5439610-354e-11e6-9c76-8dc0a9ba8745.png">

Python path for default (non-homebrew version). My assumption is that I have a pathing issue.

<img width="507" alt="screen shot 2016-06-18 at 12 25 21 pm" src="https://cloud.githubusercontent.com/assets/3529206/16173228/7eadbb24-354f-11e6-8e71-05cf4314be5f.png">

When executing `whereis python`

`/usr/bin/python`

Python version

`Python 2.7.10`

Thanks for such great content! 👍

**Comment by prakhar1989** [comment]
Hey @aaronwbrown, it seems that you are missing the dependencies required to run the flask app. Are you running this locally? If yes, did you run `pip install -r requirements.txt`? Running that command should make it work fine.

**Comment by aaronwbrown** [comment]
Hi, Prakhar. Thanks for the quick response! I had run the `pip install`, and it seems to have succeeded, prior to launching the app. 

<img width="878" alt="screen shot 2016-06-18 at 12 34 56 pm" src="https://cloud.githubusercontent.com/assets/3529206/16173267/caf6b192-3550-11e6-9223-c2f1e6186a10.png">

**Comment by prakhar1989** [comment]
Oh hmm... It seems that Flask was installed correctly. Do you might running `python` in your terminal, and entering `from flask import Flask`? Do you get the same error or does this succeed?

**Comment by aaronwbrown** [comment]
I am getting the same error. 

<img width="660" alt="screen shot 2016-06-18 at 2 31 08 pm" src="https://cloud.githubusercontent.com/assets/3529206/16173831/0a45117a-3562-11e6-8dda-cc6ab795e22a.png">

**Comment by johnfmorton** [comment]
I ended up using `pip3` and `python3` instead of `pip` and `python` when I was getting these errors. Although I don't know much about Python, I figured since the Docker container was Python 3, running it in Python 3 locally might fix the error. It did for me.

**Comment by drozzy** [comment]
@prakhar1989 Just my opinion, but I think you should consider removing the whole "run locally" section from the guide. You will only encounter problems with it. In fact, wasn't docker made to solve exactly these types of problems?

**Comment by prakhar1989** [comment]
@drozzy That's actually an excellent suggestion. Having the directions to run it locally seems to having issues for a lot of folks. I'll try rewriting this section or getting rid of this altogether.

Thanks for the suggestion! 👍

**Comment by prakhar1989** [comment]
Fixed in above commit.
