### ISSUE TITLE
[BUG] standard_init_linux.go:207: exec user process caused "exec format error  "

### ISSUE THREAD

**Issue by KamilsobC** [prakhar1989/docker-curriculum#263]
**Describe the bug**
Got
`standard_init_linux.go:207: exec user process caused "exec format error `

while trying to run:
`sudo docker run prakhar1989/static-site`

**To Reproduce**
1. Open terminal
2.  paste 'sudo docker run prakhar1989/static-site'

**Desktop (please complete the following information):**
 - OS: Ubuntu  18.04 on Jetson Nano
 - Docker Version: 19.03.06 build 369ce74a3c

**Additional context**
Trying to follow tutorial on https://docker-curriculum.com/

**Comment by KamilsobC** [comment]
root@cssjetsondev-desktop:/home/css-jetson-dev# docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 3
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.140-tegra
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.864GiB
 Name: cssjetsondev-desktop
 ID: DKQJ:6PGL:YJBT:WOOC:ENWY:ZYYA:XWGU:OTQV:2IXL:6M7A:UAHL:KAZT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by desonalleyne** [comment]
Got the same error on my RaspberryPi.
Here's my docker info:

 $ docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.75-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 874.5MiB
 Name: raspberrypi
 ID: 3VEP:A2IL:YING:SX2F:J73K:AP7S:ENHB:6JPO:JFHD:L2TD:NWOD:KKWL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by KamilsobC** [comment]
My guess is has to do something with the architecture? Since I checked on my Windows PC with Intel and worked fine. But Jetson Nano has aarch64 and yours hot armv7l and maybe that's the case.

**Comment by Tuxhedoh** [comment]
I am also having the problem on Raspberry Pi 3.
Here is my Docker Info:

Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 10
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.97-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 926.1MiB
 Name: raspberrypi
 ID: 35XL:CYB4:FBKF:WKH2:U6AI:2IRB:GYGZ:JISW:JQBO:RCAB:AYLV:7IRC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by jmjf** [comment]
According to Docker Hub, all the prakhar1989 images are x86-64. 

https://hub.docker.com/search?q=prakhar1989&type=image

You need to build an ARM-compatible image for your architecture.

Clone the repo: `git clone https://github.com/prakhar1989/docker-curriculum`
Change to the static-site subdir: `cd ~\dockerWork\docker-curriculum\static-site`
Rebuild the image on the Pi and tag it: `docker build -t jmjf/static-site-arm .`
Run the ARM image: `docker run -d -P --name static-site jmjf/static-site-arm`
Get the port: `docker port static-site` (note I didn't change the name in the `docker run` command)

You'll need to do the same basic thing for all the other prakhar1989 demos. Maybe eventually I (or someone) will figure out how to configure the repo to build images for several architectures and submit a pull request.

Reference: https://stackify.com/docker-build-a-beginners-guide-to-building-docker-images/
