### ISSUE TITLE
docker-machine ip default returns "Host does not exist: "default""

### ISSUE THREAD

**Issue by Hamblok0** [prakhar1989/docker-curriculum#27]
Not really sure what to do about this. Using OSX.

**Comment by prakhar1989** [comment]
This probably means that the docker-machine is not running. Try running `docker-machine ls` and see if the `default` machine has a `STATE = Running`. To start a machine, you can simply do `docker-machine start default`.

Here's how it looks for me
```shell
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Stopped                                       Unknown
dev       -        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.2

$ docker-machine ip dev
192.168.99.100
```

**Comment by prakhar1989** [comment]
Since I didn't hear back from you, I'm assuming you found a way ahead. 

Feel free to re-open this issue if you are stuck

**Comment by jensamoller** [comment]
Ran into same issue as @Hamblok0. 

I have included some more commands, that might be useful for you to understand the underlying issue.

```
MBP:~$ docker ps 
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                                           NAMES
18bbcf8c7b00        prakhar1989/static-site   "./wrapper.sh"      5 minutes ago       Up 5 minutes        0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   static-site

MBP:~$ docker port static-site
443/tcp -> 0.0.0.0:32768
80/tcp -> 0.0.0.0:32769

MBP:~$ docker-machine start default
Host does not exist: "default"

MBP:~$ docker-machine active
No active host found

MBP:~$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
```

**Comment by prakhar1989** [comment]
@jensamoller - Are you running Docker for Mac (Beta) or did you install Docker via the Docker Toolbox

**Comment by kierenj** [comment]
I have exactly the same thing on Windows, latest Docker for Windows download

**Comment by prakhar1989** [comment]
Ok, it seems that the **Docker for Mac** and **Docker for Windows** can run without docker-machine. Hence, you can just use `0.0.0.0` (or whatever `docker port` gives you). 

I've updated the document with the instructions for Docker v1.12. Let me know if any of use still face any issues.

**Comment by jensamoller** [comment]
@prakhar1989 Docker for Mac (Beta)

**Comment by prakhar1989** [comment]
@jensamoller: Are you still facing the same issue?

**Comment by enfeizhan** [comment]
Any update? Having exactly same issue on MAC. docker runs without docker-machine.

**Comment by swengzju** [comment]
0.0.0.0 works for me if anyone has the same issue

**Comment by w4rb0y** [comment]
I'm facing exactly same issues as @jensamoller 

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                  NAMES
405b82c8282c        ubuntu:14.04        "bash"              25 minutes ago      Up 25 minutes       0.0.0.0:45678-45679->45678-45679/tcp   echo-server2

$ docker-machine ip
Error: No machine name(s) specified and no "default" machine exists

$ docker-machine ip echo-server2
Host does not exist: "echo-server2"

$ docker-machine active
No active host found

$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

and as @swengzju said, 0.0.0.0 is working fine.

**Comment by koolrays** [comment]
can anyone please explain with an example what you mean by "0.0.0.0 is working fine"

**Comment by mnagen** [comment]
I'm facing a similar issue while running on my Ubuntu 16.04`root@ubuntu1:~/designmyconcept# docker-machine ip MACHINE_VM
Host does not exist: "MACHINE_VM"
root@ubuntu1:~/designmyconcept# docker-machine ip MACHINE_VM
Host does not exist: "MACHINE_VM"
root@ubuntu1:~/designmyconcept# docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
root@ubuntu1:~/designmyconcept# docker-machine start default
Host does not exist: "default"
root@ubuntu1:~/designmyconcept# docker-machine ip dev
Host does not exist: "dev"
root@ubuntu1:~/designmyconcept# docker-machine ip
Error: No machine name(s) specified and no "default" machine exists
root@ubuntu1:~/designmyconcept#
Could you please let me know where is this going wrong, Thanks in advance`

**Comment by debmalya** [comment]
docker-machine ip default
**Host does not exist: "default"**

uname -a
_Linux streamsqse.localdomain 2.6.32-431.29.2.el6.x86_64 #1 SMP Sun Jul 27 15:55:46 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux_
sudo docker ps
Get http:///var/run/docker.sock/v1.19/containers/json: dial unix **/var/run/docker.sock: no such file or directory**. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by hsyntnc** [comment]
Hi, 
I'm having the same issue but i have my docker machine running.

`
➜  dockerproject docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
5c947625af8d        wordpress           "docker-entrypoint..."   32 seconds ago      Up 30 seconds       0.0.0.0:32769->80/tcp   wordpress
894a792b67c9        mysql               "docker-entrypoint..."   2 minutes ago       Up 2 minutes        3306/tcp                wpmysql
a33d1f48a3ac        nginx               "nginx -g 'daemon ..."   19 hours ago        Up 19 hours         0.0.0.0:32768->80/tcp   myweb
➜  dockerproject docker-machine ip default
192.168.99.100
➜  dockerproject docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v17.06.0-ce
➜  dockerproject
`

But when i type 'http://192.168.99.100:32769/' on my browser it says this site can not be reached.

**Comment by tallcoder** [comment]
Sounds like you may need to run `docker-machine create default` first.

**Comment by aditya21891** [comment]
Thanks the command "docker-machine create default" is working

**Comment by j127** [comment]
It didn't work for me until I ran these commands as sudo (Ubuntu 16.04). Docker had written those py files as the root user from within the container, and they appeared to interfere with Docker.

```bash
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -rf {} +
```

After that the message went away.
