### ISSUE TITLE
Creating an image

### ISSUE THREAD

**Issue by wiriux** [prakhar1989/docker-curriculum#289]
Hello, 

I am stuck in this step:
>FROM python:3

>set a directory for the app
WORKDIR /usr/src/app

>copy all the files to the container
COPY . .

>install dependencies
RUN pip install --no-cache-dir -r requirements.txt

>define the port number the container should expose
EXPOSE 5000

>run the command
CMD ["python", "./app.py"]

When I build it, it says that:
python: can't open file '/usr/src/app ./app.py': [Errno 2] No such file or directory

I even made a different path but still nothing. Could you clarify how to do these steps please?

**Comment by bsbretly** [comment]
Hi @wiriux,

Where in your directory structure have you placed your Dockerfile? 

If you place your Dockerfile in the /docker-curriculum folder as suggested in the instructions (one level "up" from the flask-app folder, you'll need to append flask-app/ to all relative file path instructions. Your Dockerfile should then look something like this:

```
FROM python:3

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r flask-app/requirements.txt

# define the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./flask-app/app.py"]

```
The alternative is to just run the existing Dockerfile in the flask-app folder.

**Comment by YasinZabun** [comment]
Hi @wiriux,

I had the same problem. You should not change the Dockerfile's file extention i.e Dockerfile.txt and your current location should be ...\docker-curriculum\flask-app.
I hope this work for you.
