### ISSUE TITLE
Can't connect to ES container from flask app container

### ISSUE THREAD

**Issue by alanbernstein** [prakhar1989/docker-curriculum#29]
Following along in the tutorial, I can make it to section 3.2 without trouble, but then I have this problem:

root@ca8044fd4498:/opt/flask-app# curl 172.17.0.2:9200
curl: (7) Failed to connect to 172.17.0.2 port 9200: Connection refused

It does work fine after creating the "foodtrucks" network.

**Comment by iAreGitHugger** [comment]
I had the same. i just looked it up online and then decided to start from scratch. delete and remove everything and tart tutorial from scratch I think is best. although now I am stuck at es name conflict

**Comment by prakhar1989** [comment]
@iAreGitHugger can you share the exact error you are getting? I updated some steps last week so I think everything should be fine now. Please add more details on what error you are running into
