### ISSUE TITLE
Catnip doesn't work with python 3.10

### ISSUE THREAD

**Issue by justas-dz** [prakhar1989/docker-curriculum#308]
![image](https://user-images.githubusercontent.com/86012132/136834905-0425384c-9125-453f-a7d3-c97f7549e14b.png)

I changed the FROM to python:3.8 and it works

**Comment by mmiller1537** [comment]
I'm running into the same issue, and it looks like issues #309 and #310 are copies of this issue as well. I tried your fix in the Dockerfile and then rebuilt the image, but unfortunately that didn't resolve it on my end. I'm still digging into it but at this point I haven't found an alternate workaround.

![image](https://user-images.githubusercontent.com/76908417/137503347-bea63da9-9fa4-483a-b341-61e425972644.png)

**Comment by DariaKuzina** [comment]
Hi! I run into the same problem, it seems to be connected with this:
https://stackoverflow.com/questions/59636631/aws-cli-with-python-3-9-0a1-error-from-collections-import-mutablemapping

I'm not a python developer, so I have no idea how to fix it, so I've also tried to use python version where method we need still exists. I've used `FROM python:3.6` and it worked for me.

**Comment by AngelQC** [comment]
I did use the 3.6 version and it worked.
Also, it's complaining about a new verson if pip so I also added the command to upgrade it before the requirements,

```
# install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
```

It is still complaining about executing the installation as root, which may or may not be a concern, but it works.

Thanks for the work on this tutorial, it's nicely done!

**Comment by ZhengLin-Li** [comment]
change the Dockerfile to this and it works:
```
FROM python:3.9

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# tell the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./app.py"]

```

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/pull/313
