### ISSUE TITLE
Be more explicit in configuring AWS CLI

### ISSUE THREAD

**Issue by kjschiroo** [prakhar1989/docker-curriculum#32]
Throughout the majority of the tutorial you appear to assume the reader has not used AWS, but when we get to this line

> If you've not configured the AWS CLI on your computer before, you will also need to provide an access key and a secret key.

they are left with minimal instruction as to what an access key is, how they get it, or how to provide it to aws-cli.

**Comment by prakhar1989** [comment]
Thanks for pointing this out, I've added a link to the [official guide](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-set-up.html) which explains everything very nicely.
