### ISSUE TITLE
Version problem running tutorial

### ISSUE THREAD

**Issue by russellyoung** [prakhar1989/docker-curriculum#320]
Hi,
 (thanks for the tutorial but) it isn't working now. It gives the error that the variable MutableMapping is not available. I looked around a bit, it is a version problem. In the Dockerfile the FROM needs to be python:3.8, not Python.3 (which is now 3.10.1). With that change it works. Nice cats.

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/pull/313
