### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vistad** [prakhar1989/docker-curriculum#324]
Hello,
thank you for your course, it is good. But I could not build the Flask app due to the error:
cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
I did not find a workaround.
Hence I could not upload it to AWS etc.

**Comment by brodyd795** [comment]
I ran into this issue as well. It wasn't a blocker for me personally, since there was a lot of other good content that I was able to learn from the curriculum, but wanted to point this out.

**Comment by prakhar1989** [comment]
https://github.com/prakhar1989/docker-curriculum/pull/313
