### ISSUE TITLE
Very nice course , but having problems with AWS EB deployment

### ISSUE THREAD

**Issue by Partha-Mukherjee-G2H** [prakhar1989/docker-curriculum#33]
I try to deploy the catnip application, but unfortunately don't see the expected GIFs when I go to the URL for the Environment. 
Just see the generic "Congratulations! Your docker container is running in EB".
It am guessing that the Container port 5000 is not mapped to port 80.
Does this need to be specified in Dockerrun.aws.json?

**Comment by prakhar1989** [comment]
Are you having trouble in getting to run this locally or on AWS?

**Comment by Partha-Mukherjee-G2H** [comment]
Hi Prakhar, thanks for the response. The problem is for AWS only. I think the way that you have it defined will expose port 5000 in the container, but generally the Security policy will not expose this port externally. You can either create a reverse proxy to map a "normal" port such as 80, or you can do this using the Dockerrun.aws.json v2 which enables the mapping of port from host to container (i.e. like the -P docker run option), i.e. 
    "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 80
        }

**Comment by prakhar1989** [comment]
Ah, that's a valid point. When I last tried this out AWS was reverse-proxy'ing the exposed port by default and hence I didn't need to add anything extra. Given that you've raised an issue, I'll give it a shot again this weekend and see the curriculum / dockerfile needs an update. :)

**Comment by Partha-Mukherjee-G2H** [comment]
Sounds good. Once again, I think this is a great introduction tutorial! Thank you for putting it together!
