### ISSUE TITLE
[BUG] Catnip fails to run 

### ISSUE THREAD

**Issue by mike-dooley66** [prakhar1989/docker-curriculum#332]
When I try to run the Flask app in the Catnip example I get the following error:

Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)

**To Reproduce**

1. Download the repo for the Flask App 
2. Build the container --> docker build -t yourusername/catnip .
3. Run the container --> docker run -p 8888:5000 yourusername/catnip

**Expected behavior**
Output should indicate that the webserver is running

**Comment by aanchal-adk** [comment]
There's a simple fix to this issue. 
In the requirements.txt file update the version of flask to 2.0.1 or above:`Flask==2.0.1`
[Here](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/#:~:text=json'%20from%20itsdangerous-,Solution%201%20%E2%80%93%20Upgrade%20the%20Flask%20to%20latest%20version%20%3E%202,1%20or%20above.)'s more info in this issue.

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/pull/313
