### ISSUE TITLE
Not able to build the image 

### ISSUE THREAD

**Issue by imlight** [prakhar1989/docker-curriculum#39]
Hi, Thanks for the tutorial document. 
I was able to follow it till  para 2.4 . 

During build I get below error 

light@light-OptiPlex-7010:~/docker-curriculum/flask-app$ docker build -t imlight/lightimagerepo .
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM python:3-onbuild
 Executing 3 build triggers...
Step 1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 6442f9922bcc
Collecting Flask==0.10.1 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f715d12b4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/

I didnt had any issue till just before this.

I believe this has something to do with http proxy , but i have these variables shared in environment 

echo $http_proxy && echo $https_proxy
http://XXXXXXXX:8080/
https://XXXXXXXX:8080/

**Comment by prakhar1989** [comment]
Still getting the same issue?

**Comment by nathanbowness** [comment]
I've gotten the exact same issue. Not sure how to fix it.

**Comment by prakhar1989** [comment]
Are you behind a proxy? Try running `pip install flask` in your host machine and see if that works. That might help explain why your HTTP request is failing.
