### ISSUE TITLE
Update section 3.2 for latest docker

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/docker-curriculum#43]
Changes are no longer made in `/etc/hosts`. Update this section to reflect the last stable version.

**Comment by jschlieber** [comment]
Just following along the (btw awesome) tutorial. What is the right way to get the correct `es` entry into `/etc/hosts` now?

**Comment by prakhar1989** [comment]
Networking in Docker is handled via DNS now. So /etc/hosts will not be changed. More info [here](https://docs.docker.com/engine/userguide/networking/configure-dns/)

**Comment by jschlieber** [comment]
Nice! Thanks for the quick response.

**Comment by prakhar1989** [comment]
Updated to remove this section which is no longer true for docker `1.18`. Thanks!
