### ISSUE TITLE
Refused to connect 0.0.0.0

### ISSUE THREAD

**Issue by gdabli** [prakhar1989/docker-curriculum#44]
Hi Prakhar,

Thanks for the awesome tutorial. i some one issue here. after running python.py I am getting 
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

but when i am hitting url on local i am getting 0.0.0.0 refused to connect. 
<img width="730" alt="screen shot 2016-09-13 at 11 47 10 am" src="https://cloud.githubusercontent.com/assets/9170414/18480754/d8bf4ac8-79a7-11e6-8608-c5257f4b9dce.png">

**Comment by prakhar1989** [comment]
Can you tell me what version of Docker are you running? Docker for Mac or Docker via the Docker toolbox?

**Comment by gdabli** [comment]
I am using docker for mac

Docker version 1.12.0, build 8eab29e

**Comment by prakhar1989** [comment]
Can you please paste exact that you're running? Also are you running on your local machine or inside the container?

**Comment by gdabli** [comment]
following your tutorial, i downloaded docker for mac. I am running on my local (on my mac). please see the below attached screenshot.
<img width="757" alt="screen shot 2016-09-13 at 11 54 03 am" src="https://cloud.githubusercontent.com/assets/9170414/18481084/eccce1f0-79a8-11e6-8768-772c5fadc6ca.png">

**Comment by prakhar1989** [comment]
You mentioned `after running python.py I am getting`. What command are you referring to and where are you running this?

**Comment by gdabli** [comment]
<img width="1198" alt="screen shot 2016-09-13 at 11 59 42 am" src="https://cloud.githubusercontent.com/assets/9170414/18481294/af306140-79a9-11e6-87a1-6926d4882da7.png">
running app.py from above. I get output as 
<img width="785" alt="screen shot 2016-09-13 at 12 00 07 pm" src="https://cloud.githubusercontent.com/assets/9170414/18481314/c604820c-79a9-11e6-8572-1f48a13e75bb.png">

but when i am trying to see the images on browser, i see below error.
<img width="730" alt="screen shot 2016-09-13 at 11 47 10 am" src="https://cloud.githubusercontent.com/assets/9170414/18481357/e6ffd254-79a9-11e6-8f0b-d9d9d1fe36e1.png">

**Comment by prakhar1989** [comment]
This might not fix it, but try running without the sudo. Also, you can try to change the `app.run(host...)` line in the python file and just use `app.run`. Does that work?

**Comment by gdabli** [comment]
it worked without sudo. but i didn't understand how sudo is making a difference.
