### ISSUE TITLE
"refused to connect" error when trying to run the custom built image

### ISSUE THREAD

**Issue by PGryllos** [prakhar1989/docker-curriculum#45]
For some reason after I run the `docker run -p 8888:5000 <user_name>/catnip` (although I get the message that the site is running on http://0.0.0.0:5000/) I don't seem to be able to access the address. 
When I click on the link I get: This site can’t be reached 0.0.0.0 refused to connect.

**Comment by PGryllos** [comment]
Sorry I was looking at the wrong address

**Comment by chrismark** [comment]
In windows 10, I wrongly assumed that since it says 0.0.0.0, I had to change app.py so it starts it at 127.0.0.1 or localhost. But actually its fine as is, just go to localhost:8888.
