### ISSUE TITLE
can't git clone loccally "git://github.com/prakhar1989/docker-curriculum/tree/master/flask-app"

### ISSUE THREAD

**Issue by beylistan** [prakhar1989/docker-curriculum#49]
![selection_001](https://cloud.githubusercontent.com/assets/22915582/19486061/c91fde00-9565-11e6-8dc8-0fa15054c3e3.png)
![git_auth](https://cloud.githubusercontent.com/assets/22915582/19486354/c3acde40-9566-11e6-8f9c-29b36b4769c5.png)

**Comment by odinserj** [comment]
Clone the whole repository, then change the directory, instead of trying to clone just the directory:

```
git clone https://github.com/prakhar1989/docker-curriculum.git
cd docker-curriculum/flask-app
```
