### ISSUE TITLE
docker login

### ISSUE THREAD

**Issue by therzka** [prakhar1989/docker-curriculum#5]
It's possible I did the setup wrong but I thought it would be useful to add a note before the `docker push` section to run `docker login` if you get `unauthorized: access to the requested resource is not authorized`

absolutely love the tutorial, thanks!

**Comment by prakhar1989** [comment]
Hi @therzka - are you referring to [section 2.5](http://prakhar.me/docker-curriculum/#docker-aws). I actually do mention that you need to login but its **below** the `push` command. Do you recommend that I move that line up?

<img width="813" alt="screen shot 2016-01-12 at 11 54 22 pm" src="https://cloud.githubusercontent.com/assets/649249/12285409/d36e6652-b987-11e5-91f3-8da2a5d42c74.png">

Glad that you're liking the tutorial :grinning:

**Comment by prakhar1989** [comment]
Oh wait, I don't actually mention `docker login`. Stupid me.. Let me fix it right away.

**Comment by therzka** [comment]
:+1: thanks!

**Comment by vfinotti** [comment]
I was about to report the same issue. IMO, the sentence "If this is the first time you are pushing an image, the client will ask you to login." is quite misleading. I had the impression that immediately after the ```docker push``` command, docker would automatically ask for my credentials. Perhaps this was just me, but something like "If this is the first time you are pushing an image, you should first login at the client with the ```docker login``` command." would be more explicit.
