### ISSUE TITLE
Foodtruck app doesn't seem to work

### ISSUE THREAD

**Issue by pankevich** [prakhar1989/docker-curriculum#51]
Only the map of SF gets displayed. I found one issue with the app.py: on line 39, load_data_in_es() gets called if safe_check_index() fails instead of when it succeeds. After fixing it, the app now does print "loading data in elasticsearch", and the number of trucks it loaded, but the webpage still doesn't display any trucks, and I'm out of ideas. From within the foodtrucks-web image, curl test to es works fine.

**Comment by prakhar1989** [comment]
Can you tell me how are you trying the app? I just did the following and everything works fine - 
```
$ git clone https://github.com/prakhar1989/FoodTrucks
$ cd FoodTrucks
$ docker-compose up
```

Also, what docker and docker-compose versions are you running?

**Comment by pankevich** [comment]
I did the same thing as you. 
$docker --version
Docker version 1.12.2, build bb80604
$docker-compose --version
docker-compose version 1.9.0-rc1, build 28788bd
I was able to push the last image in the tutorial to the hub (it took a LONG time to appear there, like 30 minutes or so) and start the ECS cluster. You can see the result at http://54.162.210.58/ - no trucks.

**Comment by pankevich** [comment]
Also, if you run the app.py by itself, the message "loading data in elasticsearch" only appears of you make the fix which I originally described.

**Comment by davidtseng** [comment]
I've enjoyed this tutorial but also experience a problem near the end similar to comment above with deply on ECS:

Great! Now let's run the final command that will deploy our app on ECS!
$ ecs-cli compose --file aws-compose.yml up
...
If everything went well, you should see a desiredStatus=RUNNING lastStatus=RUNNING as the last line.

In the tutorial there isn't any suggestions on what to do if everything doesn't go well with that step. Looks like I'll need to do some digging as my containers also don't start with lastStatus=STOPPED.

Did something change?

**Comment by prakhar1989** [comment]
@davidtseng Sure... I'll give it a shot again to see if something changed on the AWS front. Can you see through the logs on the platform, as they contain useful information if the configuration got messed up somewhere.

**Comment by davidtseng** [comment]
@prakhar1989 Do you have a quick tip on the best place to look? I have not used ECS or EC2 much before so I spent an hour last night trying to find out where the logs are and was not successful. The Foodtruck app worked locally by the way in my case, I didn't have the original issue reported about the app not functioning. Thanks Prakhar, great work.

**Comment by denny64** [comment]
any updates on this? I'm getting the same issue

**Comment by 9929105** [comment]
I have a theory: 
Elasticsearch now required 2 Gb of mem to run. 
I did the following changes and now it worked: 

Change the AWS machines to t2.large. (it will charge you a little money)
change the aws-compose.yml to the following: 

es:
  image: elasticsearch:2.3
  cpu_shares: 100
  mem_limit: 2046m 
web:
  image: teacherjacob/foodtrucks-web
  command: python app.py 
  cpu_shares: 100
  mem_limit: 256m
  ports:
    - "80:5000"
  links:
    - es

**Comment by thomasphillips3** [comment]
I had this same problem. Specifying the version for `elasticsearch` in the `docker-compose.yml` fixed it for me. The [tutorial](https://docker-curriculum.com) has

```
version: "2"
services:
  es:
    image: elasticsearch
...
```

But this works: 
```
version: "2"
services:
  es:
    image: elasticsearch:2.3
...
```
