### ISSUE TITLE
/etc/hosts file isn't updated with new containers

### ISSUE THREAD

**Issue by pankevich** [prakhar1989/docker-curriculum#52]
After the foodtrucks bridge is created, and the elasticsearch and foodtrucks-web are launched with --net foodtrucks, the foodtrucks-web's /etc/hosts does not contain an entry for the es host. Despite that, connections to the es host from foodtrucks-web do work. I am not sure how, but they do. Does docker daemon take care of this?

**Comment by prakhar1989** [comment]
Yes, that is right. No changes are made in `/etc/hosts` and that's because in newer versions of Docker, they switched networking to DNS based. You can read more about it [here](https://docs.docker.com/engine/userguide/networking/configure-dns/).

> As of Docker 1.10, the docker daemon implements an embedded DNS server which provides built-in service discovery for any container created with a valid name or net-alias or aliased by link. The exact details of how Docker manages the DNS configurations inside the container can change from one Docker version to the next. So you should not assume the way the files such as /etc/hosts, /etc/resolv.conf are managed inside the containers and leave the files alone and use the following Docker options instead.
