### ISSUE TITLE
Tutorial doesn't say how to exit a docker box

### ISSUE THREAD

**Issue by andyhasit** [prakhar1989/docker-curriculum#53]
In the [tutorial](https://prakhar.me/docker-curriculum/) shortly after the instruction to run __docker run -it busybox sh__ it says:

> Once everything stops working, you can exit the container

But it doesn't tell you how to do that! (Its ctrl+p followed by ctrl+q)

**Comment by prakhar1989** [comment]
Thanks for pointing out this issue! @tedyoung just sent a PR to fix this so it should now be understandable. =)
