### ISSUE TITLE
Problem with Elasticsearch v5

### ISSUE THREAD

**Issue by markronquillo** [prakhar1989/docker-curriculum#58]
Need to update the memory size of virtualbox instance to at least 2gb.

Elasticsearch v5 introduces an error "max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]".

This can be fixed by running sysctl -w vm.max_map_count=262144 on your docker machine instance. You can access it through docker-machine ssh.

**Comment by prakhar1989** [comment]
Fixed in #59
