### ISSUE TITLE
Missing docker networking in docker-compose chapter

### ISSUE THREAD

**Issue by rickpeters** [prakhar1989/docker-curriculum#6]
First of all: a very well built up and well written tutorial. Kudo's and compliments to you. Even new things like docker networking were integrated.
Since linking the containers without networking is easy enough, the networking part is not strictly necessary. I therefore expected that you would have used the networking part in the docker-compose file also, but you didn't. I think it would be great if you mention the (upcoming) networking support (https://docs.docker.com/compose/networking/) and also explain the subtle difference between the `link` instruction in docker-compose and the `--network` you use in the networking example. Or as alternative, explain linking your containers by hand, enhancing that using networking and then go on to docker-compose (which still has the challenge in service discovery based on the generated names for containers :-) )

Anyway, again, lot's of respect for your great tutorial, I'm bookmarking it as reference to give to colleagues who want to learn more about Docker!

**Comment by prakhar1989** [comment]
Hey Rick! Thanks a lot for the kind words. And thank you for creating the issue - this is exactly kind of real-world experience I was hoping the community would educate me on!

> Since linking the containers without networking is easy enough, the networking part is not strictly necessary.

Pardon me if I mis-understood this, but are you suggesting that I should've used links over network in the tutorial? The reason I left out docker links was because it's been [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) and the documentation suggests using `network` over links wherever required.

> I therefore expected that you would have used the networking part in the docker-compose file also, but you didn't. I think it would be great if you mention the (upcoming) networking support 

This is awesome! I had no absolutely no clue that something like this even existed. I'll surely go through the documentation and see how I can incorporate this into the tutorial.

I'll keep this issue open until I figure out to a way to add this section into the tutorial. Would you be okay on doing a reviewing once I have a draft written? I'd love to get feedback from someone who has experience with the feature.

Thank you once again for creating this issue and telling me about this feature. 

I hope that your colleagues find the tutorial useful too :)

Best,

**Comment by rickpeters** [comment]
Hi Prakhar,

that's indeed what I meant. What you see here is an example of Docker changing functionality with lightning speeds ;-)
However it still states that it is *expected to be deprecated* and luckily it still works, because docker networking depends on fairly new linux kernels which are not always available to users in corporate environments.
The docker-compose networking is still experimental (you need the `--x--networking` flag), however it shows lots of promise (certainly if you add *docker-machine*, *swarm* and multi-host networking into the mix :-)

So in conclusion, I think using networking is the right way to explain things in your tutorial, but in the docker-compose section I would mention that this is still based on the legacy linking method which will be deprecated. Teh point being that from a functional point-of-view the effect of manual networking and docker-compose linking is the same, but from a technical point of view something different is happening and readers should expect changes on this in the near future of docker-compose.

I would certainly be willing to do a quick review when needed.

regards,
Rick

**Comment by prakhar1989** [comment]
Hi Rick! 

Thanks for the clarification. I just pushed a commit with the changes you had proposed. You can read the  changes in the [diff](https://github.com/prakhar1989/docker-curriculum/commit/4a1d4b081f7561f817f9f93ee6f54dd55323557f?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) and see if it makes sense.

Looking forward to hearing your thoughts!

**Comment by rickpeters** [comment]
Hi Prakhar,

sorry it took me a while to give you a response. I think you made a great addition. I really like your exploratory way of writing this up. It keeps readers attached and curious I think.

You solved the *experimental* character of compose also very nice including the *resolving problem*.
I don't know for sure (didn't actually try), but I think that if you use the feature mentioned in [configure how services are published](https://docs.docker.com/compose/networking/#configure-how-services-are-published) you should be able to get the *ES* alias the web-application expects by using the `container_name` option.

What was also interesting to read is that compose will create an *alias* based on the short name (without the instance number), this should give some idea into how *service-discovery* will work from compose point-of-view when upscaling the container on the same docker engine :-). They will just publish under the same short name.

Keep up the good work!

regards,
Rick

**Comment by prakhar1989** [comment]
Hey Rick!

Thanks a lot for the kind words! Also, thank you for pointing me to the `container_name` configuration. I'll add a quick note about this and then publish these changes online. 

Thanks again for your making the tutorial better.

Best,
