### ISSUE TITLE
Can't build flask app

### ISSUE THREAD

**Issue by flux627** [prakhar1989/docker-curriculum#60]
I tried running the command as per the tutorial, but got this error:
```
$ docker build -t flux627/catnip .
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM python:3-onbuild
Pulling repository docker.io/library/python
Tag 3-onbuild not found in repository docker.io/library/python
```
Any suggestions?

**Comment by flux627** [comment]
Tried it again, and it worked... how often does this happen? I'd imagine that this wouldn't be acceptable in a production environment.

**Comment by prakhar1989** [comment]
I've not seen it happen - might be a one-off errors. In my experience, docker builds typically happen before production (staging etc) and on success, the containers are shipped to production.
