### ISSUE TITLE
How to debug stopped ecs instances

### ISSUE THREAD

**Issue by mhuntemann** [prakhar1989/docker-curriculum#61]
Hi!

Thanks for the tutorial. Really enjoyed.
Had a little hick-up with the 'ecs-cli up ...' command, since I didn't get right away that I really need to install and configure the aws tool. But I got it working.
The docker compose ran fine for me locally, but when I ran the 'ecs-cli compose ...' command the es instance stopped with exit code 1.

user@computer:~/dev/FoodTrucks$ ecs-cli compose --file aws-compose.yml up
INFO[0000] Using ECS task definition                     TaskDefinition="ecscompose-FoodTrucks:1"
INFO[0000] Starting container...                         container="ab4f0282-60d2-45ff-ba07-58050a34c90c/web"
INFO[0000] Starting container...                         container="ab4f0282-60d2-45ff-ba07-58050a34c90c/es"
INFO[0000] Describe ECS container status                 container="ab4f0282-60d2-45ff-ba07-58050a34c90c/web" desiredStatus=RUNNING lastStatus=PENDING taskDefinition="ecscompose-FoodTrucks:1"
INFO[0000] Describe ECS container status                 container="ab4f0282-60d2-45ff-ba07-58050a34c90c/es" desiredStatus=RUNNING lastStatus=PENDING taskDefinition="ecscompose-FoodTrucks:1"
INFO[0012] Describe ECS container status                 container="ab4f0282-60d2-45ff-ba07-58050a34c90c/web" desiredStatus=RUNNING lastStatus=PENDING taskDefinition="ecscompose-FoodTrucks:1"
INFO[0012] Describe ECS container status                 container="ab4f0282-60d2-45ff-ba07-58050a34c90c/es" desiredStatus=RUNNING lastStatus=PENDING taskDefinition="ecscompose-FoodTrucks:1"
INFO[0024] Stopped container...                          container="ab4f0282-60d2-45ff-ba07-58050a34c90c/web" desiredStatus=STOPPED lastStatus=STOPPED taskDefinition="ecscompose-FoodTrucks:1"
INFO[0024] Stopped container...                          container="ab4f0282-60d2-45ff-ba07-58050a34c90c/es" desiredStatus=STOPPED lastStatus=STOPPED taskDefinition="ecscompose-FoodTrucks:1"
user@computer:~/dev/FoodTrucks$ ecs-cli ps
Name                                      State                Ports  TaskDefinition
ab4f0282-60d2-45ff-ba07-58050a34c90c/web  STOPPED                     ecscompose-FoodTrucks:1
ab4f0282-60d2-45ff-ba07-58050a34c90c/es   STOPPED ExitCode: 1         ecscompose-FoodTrucks:1
user@computer:~/dev/FoodTrucks$

I checked my ecs console, but couldn't find any hits why the es instance failed.
Can you give me any hints on how to debug this to find out why it works locally, but fails on AWS?

Thanks heaps,
Marcel

**Comment by adrianmcli** [comment]
I'm having the same issue, @mhuntemann did you find out what was wrong?

**Comment by denny64** [comment]
any updates on this?

**Comment by Cesaros** [comment]
Same problem here :(

**Comment by mahesh-projects** [comment]
Would be great to get some pointers to solve this issue!

**Comment by jeremyyeo** [comment]
Can verify that @mahesh-projects's tweak worked for me too. Guessing this has something to do with the fact that newer versions of elasticsearch need more memory and thus will not run on t2.micro instances?

**Comment by prakhar1989** [comment]
Hi, this section has been updated to use the latest ES version (`7.6.*`) and i've also update the compose file that AWS will be happy with.

Please try it again and feel free to re-open the bug if there are still any issues.
