### ISSUE TITLE
Update section 2.5 Docker on AWS

### ISSUE THREAD

**Issue by alejandrox1** [prakhar1989/docker-curriculum#63]
The tutorial is great but the section `2.5 Docker on AWS` needs to be updated as AWS changed the setup options and most of this sections would need rewriting.

**Comment by arafatm** [comment]
Agreed. I'm using AWS for the first time and the options are different enough that I'm stuck.

**Comment by prakhar1989** [comment]
Done - added new screenshots. Let me know if any of it is still confusing.
