### ISSUE TITLE
Had to manually install flask for the Flask app

### ISSUE THREAD

**Issue by sagarkal** [prakhar1989/docker-curriculum#64]
Hi Prakhar,

I was going through your docker tutorial where you suggested to clone the docker-curriculum repo and run the flask app. However, when I ran the command

pip install -r requirements.txt

It did not install the Flask module. I had to manually install it by running

pip install flask

**Comment by prakhar1989** [comment]
Hi Sagar - I was unable to reproduce this error. I freshly cloned the repo, created a virtualenv (optional), and ran `pip install -r requirements.txt` which successfully installed Flask.

**Comment by prakhar1989** [comment]
Let me know if this is still an issue.
