### ISSUE TITLE
/etc/hosts issue

### ISSUE THREAD

**Issue by sajeesh84** [prakhar1989/docker-curriculum#66]
After starting the es with new network, I ran the flaskapp with bash on the new network.
When I open /etc/hosts file i donot se the IPs for ES updated here. However the app is working fine, accessible as expected

Can we get away even if Hosts file is not updated with the container-host/ip values?

**Comment by prakhar1989** [comment]
Yup, in later version Docker doesn't rely on `/etc/hosts`. Refer to #43.
