### ISSUE TITLE
No "es" related things added to /etc/hosts

### ISSUE THREAD

**Issue by gengyabc** [prakhar1989/docker-curriculum#67]
Hi, I am working on the user-defined network and after I run this command:
`$ docker run -it --rm --net foodtrucks prakhar1989/foodtrucks-web bash`

/etc/hosts file is like this:
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.3	5c76db6f18d1
```

The strange thing is that `curl es:9200` works fine and after run:
`docker run -d --net foodtrucks -p 5000:5000 --name foodtrucks-web prakhar1989/foodtrucks-web`
I can visit the app. So except the "/etc/hosts" file, everything works fine.

Why this happened? Thank you very much.

**Comment by drozzy** [comment]
You sure you inspecting the right `/etc/hosts` file?

**Comment by prakhar1989** [comment]
@gengyabc You're doing everything fine. In later versions, Docker doesn't rely on /etc/hosts. Refer to #43.
