### ISSUE TITLE
Has the Tutorial been taken down?

### ISSUE THREAD

**Issue by sajeesh84** [prakhar1989/docker-curriculum#68]

**Comment by tedyoung** [comment]
To clarify the problem that @sajeesh84 mentions, the link to http://prakhar.me/docker-curriculum/ results in a 404 Page Not Found.

**Comment by prakhar1989** [comment]
Sorry - I porting my website over to new Firebase and forgot to migrate the other sites. As of know, you can access the curriculum at http://prakhar1989.github.io/docker-curriculum/

**Comment by prakhar1989** [comment]
It's back up at https://prakhar.me/docker-curriculum/

Thanks a lot for letting me know!
