### ISSUE TITLE
Static Site Question

### ISSUE THREAD

**Issue by sajeesh84** [prakhar1989/docker-curriculum#70]
When I run the static site using docker run -dp 8888:80 prakhar1989\static-site, everthing works as expected.
I was trying to understand how is the HTML and CSS passed into the container(to ngnix)?
I do see : COPY html /usr/share/nginx/html
in this statement what the is source of html from where it is copied? 
We didn't really put it on to local machine.

**Comment by prakhar1989** [comment]
That's because the [container](https://hub.docker.com/r/prakhar1989/static-site/) already has the required html / css files which were copied over when I built the container.

**Comment by sajeesh84** [comment]
For the container to get the file it has to be specified in the Image, correct?

**Comment by prakhar1989** [comment]
Yes, that's right!
