### ISSUE TITLE
Section 4.2: Step1/1 Copy requirements.txt - no such file or directory

### ISSUE THREAD

**Issue by lhardie** [prakhar1989/docker-curriculum#74]
I'm at step 4.2 where I am building an image, and in doing the following:
docker build -r myusernamehere/catnip .

I get the following error:
Step 1/1 : COPY requirements.txt /usr/src/app/
lstat requirements.txt: no such file or directory

I am in Docker Toolbox on Windows 7.

**Comment by lhardie** [comment]
well I feel silly.  I was running the command from a Dockerfile located just outside the flask-app directory. The documentation wasn't clear that I should be overwriting the existing Dockerfile inside this folder... I was confused.

**Comment by prakhar1989** [comment]
No problem :)

**Comment by zhanglanqing** [comment]
haha, that is the problem, thanks :->
