### ISSUE TITLE
Docker Compose does not allow discovery by service name

### ISSUE THREAD

**Issue by adrianmcli** [prakhar1989/docker-curriculum#75]
I got to section 3.3 in the tutorial and ran `docker-compose up`. Unfortunately, the python flask app was not able to find the elastic search instance under the name `es`. I can confirm that the network `foodtrucks_default` was created, so the lack of a network is not the issue.

I was also able to run `docker network inspect foodtrucks_default` to confirm that both instances were on the same network.

It turns out that Docker Compose now creates a name for each instance like this:

```json
{
  "Containers": {
    "958dcdad6b04e763b7fef559c4009d433022ca3788ef3d2f107f3ef651059535": {
      "Name": "foodtrucks_web_1",
      "EndpointID": "b262f279d4df95d2d05ff20f12fb22987dbce75ccb132bc2763641cf6d12c082",
      "MacAddress": "02:42:ac:12:00:03",
      "IPv4Address": "172.18.0.3\/16",
      "IPv6Address": ""
    },
    "f5cc8fc52565b67ca2373a9aded90e57c5b95bf18c8c856ce39eb9ff9bc4626f": {
      "Name": "foodtrucks_es_1",
      "EndpointID": "d2a51ecc6fb1eafe8ca81db200b7e4998a6ab9cfd74f4117f949291c7a23cdc0",
      "MacAddress": "02:42:ac:12:00:02",
      "IPv4Address": "172.18.0.2\/16",
      "IPv6Address": ""
    }
  }
}
```

^ An excerpt from running `docker network inspect foodtrucks_default`.

So (in the flask app) once I changed:

```py
es = Elasticsearch(host='es')
```

to

```py
es = Elasticsearch(host='foodtrucks_es_1')
```

It then finally worked. Can anyone offer some insight on why this is the case and link to some official documentation that points out this difference? Thanks.

**Comment by davidcpell** [comment]
Did you ever find anything out? I had the same problem except it doesn't work for me even when I change the value in `app.py`. It's weird because if I comment out `docker-compose.yml` so it *only* starts elasticsearch, then manually run a foodtrucks container with `docker run -it --rm -p 5000:5000 --network foodtrucks_default davidcpell/foodtrucks-web bash` and ran `python app.py` without any problems.

**Comment by adrianmcli** [comment]
Yeah I don't recall what the problem was either. My advice would be to just keep going with the tutorial since the concept is easy enough to understand without having to try it out completely.
