### ISSUE TITLE
SF Food Truck App shows blank screen

### ISSUE THREAD

**Issue by rkraman** [prakhar1989/docker-curriculum#76]
The Docker for beginners tutorial is excellent.  I was able to learn a lot and understand.  Kudos for the great work.  I followed your instruction on building the SF Food Trucks app and after running and launching the web page http://0.0.0.0:5000/  I get a blank page with just the Masthead

![image](https://cloud.githubusercontent.com/assets/24415607/24303385/c0b2aa88-1083-11e7-8307-060f0c44761f.png)

Not sure what I did wrong.  I even tried your app instead of building one and got the same result.

Thanks

-RK

**Comment by prakhar1989** [comment]
Can you inspect the console and see what error are you getting?

**Comment by prakhar1989** [comment]
Let me know if this is still an issue.

**Comment by JahidGit2017** [comment]
I have tried this app, but in my case the location dots are not showing in the Chrome browser.
![DeepinScreenshot_dde-desktop_20191004131646](https://user-images.githubusercontent.com/30212252/66188543-4e5ba080-e6a9-11e9-855d-564deebbc673.png)
