### ISSUE TITLE
Excellent Tutorial "Dockers for Beginners"

### ISSUE THREAD

**Issue by mohitag80** [prakhar1989/docker-curriculum#78]
Hi Prakhar,

You did a great work in writing a tutorial on Docker for beginners. Just within few hours I am feeling myself at a level above beginner in Docker and micro services technology. Thanks a lot ! 

I have few initial queries as per my requirements. Though I am searching their answers on my own, it will help if you can guide me further.

1) Is there any full version RHEL Linux OS Docker Image available where we can install Application Servers and Database as we do in our Organizational environment?

2) I need to create an Docker image with IBM Websphere Application Server (non-liberty profiles) and IBM DB2, is there any image available for it?  

Will appreciate your response and guidance.

Thanks,

Mohit Agrawal

**Comment by prakhar1989** [comment]
Glad to hear you liked the tutorial. Since I do not experience with either these enterprise-y tech, my guess is as good as yours. If I were you, I'd just search in the [docker registry](https://hub.docker.com/) to see what I can find.
