### ISSUE TITLE
The link to sf-foodtrucks.xyz - its NSFW

### ISSUE THREAD

**Issue by dan-rose** [prakhar1989/docker-curriculum#79]
I don't think I can click on it again to take a screen shot... not without getting sacked anyway

Dan

**Comment by prakhar1989** [comment]
I'm so sorry about this. My ownership over the domain expired over a year ago and I forgot to remove all links to it from the curriculum. Removing it right now. 

Thanks for letting me know!

**Comment by prakhar1989** [comment]
Done! Thanks again!
