### ISSUE TITLE
first time docker push does not always prompt for login

### ISSUE THREAD

**Issue by christopherdabney** [prakhar1989/docker-curriculum#81]
Section (2.5) suggests that docker push will invoke a docker login, but this did not occur for me. After getting the error message "denied: requested access to the resource is denied", I found that I needed to run the command docker login before running docker push.

**Comment by prakhar1989** [comment]
Thanks for notifying :) I'll update the curriculum with this info!

**Comment by christopherdabney** [comment]
I would also note that the AWS environment setup flow is different from what you have. The Dockerrun.aws.json upload still does the job, but I could not figure out how to set the ID. Still works, but took some figuring out, which was quite daunting for someone who has never worked on AWS before.
Overall, though, yours is a great tutorial. One of the most best explanations of docker I have seen! Thank you! 

    On Sunday, April 16, 2017 8:53 AM, Prakhar Srivastav <notifications@github.com> wrote:
 

 Closed #81.—
