### ISSUE TITLE
# docker-machine ip MACHINE_VM Host does not exist: "MACHINE_VM"

### ISSUE THREAD

**Issue by mnagen** [prakhar1989/docker-curriculum#87]
I'm facing an issue after installing docker-machine on my Ubuntu 16.04, could any one please help me with this, thanks in advance

````   

# docker-machine ip MACHINE_VM
Host does not exist: "MACHINE_VM"

# docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

# docker-machine start default
Host does not exist: "default"

# docker-machine ip dev
Host does not exist: "dev"

# docker-machine ip
Error: No machine name(s) specified and no "default" machine exists

**Comment by DrOzturk** [comment]
I think you want to use local docker. Docker Machine enables you to provision multiple remote Docker hosts on various flavors of Linux. (Source: https://docs.docker.com/machine/overview/#what-is-docker-machine)

You better follow from this tutorial:
https://docs.docker.com/get-started/
