### ISSUE TITLE
Amazon ECS CLI now supports compose version 2 file format

### ISSUE THREAD

**Issue by antoniokov** [prakhar1989/docker-curriculum#88]
Since the support for the compose version 2 file format [was added](https://github.com/aws/amazon-ecs-cli/issues/86) to Amazon ECS CLI, there's no need to create a separate `aws-compose.yml` config.

Removing the corresponding section would make the tutorial even clearer and shorter than it is.

**Comment by prakhar1989** [comment]
I've updated that section to reflect this change. However, keeping separate files allows us to add aws specific config in docker compose as I've added, which is why I think it's better to keep the files separate.
