### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by juniorUsca** [prakhar1989/docker-curriculum#90]
Hi, I can translate the article to spanish. How should I proceed?

**Comment by pardoman** [comment]
https://translate.google.com/translate?hl=en&sl=en&tl=es&u=https%3A%2F%2Fdocker-curriculum.com%2F

**Comment by hejiaji** [comment]
@pardoman hahaha, that's not funny

**Comment by prakhar1989** [comment]
@juniorUsca Sure! Feel free to translate it to spanish! I'd recommend creating a new branch on this repo and sending in a pull-request when you are done. I can merge it in and then link to from the main guide.
