### ISSUE TITLE
Problems with aws-compose.yml and with second ecs-cli configure example

### ISSUE THREAD

**Issue by kreig303** [prakhar1989/docker-curriculum#94]
Hi,

Issues with the following...

-  `./aws-compose.yml` needs to have the same `image: elasticsearch:2.3` specified as in  `docker-compose.yml` or there are downstream build issues.
- `ecs-cli configure --region us-east-1 --cluster foodtrucks` command in final section — while accurate — also clears out any pre-existing auth info and causes an error to be thrown unless the Access Key and Secret is reinvoked.

Thought about creating PRs but that seemed needless unless you'd like me to.

**Comment by ndench** [comment]
:+1: I was having a problem with `ecs-cli compose up` until I changed the image to `elasticsearch:2.3`. I think PRs would definitely be helpful to others who don't think to check the github issues page.

**Comment by prakhar1989** [comment]
@kreig303 Oh yes, a PR would be super awesome! Thanks a lot for taking a look at this!
