### ISSUE TITLE
2.1 Static Sites does not run on raspberry pi 3

### ISSUE THREAD

**Issue by hjw** [prakhar1989/docker-curriculum#96]
Yet another example from docker provided tutorials which doesn't run on a raspberry pi3.

Status: Downloaded newer image for prakhar1989/static-site:latest
standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by MajorLee95** [comment]
> prakhar1989

It is normal. In docker hub this image is tagged Linux/amd64 so it is an image for Intel like processor not for ARM archi. I have the same problem with a FriendlyArm nanoPC-T4 ! Snif
