### ISSUE TITLE
Tutorial says not to use "links", then uses a docker-compose.yml with "links"

### ISSUE THREAD

**Issue by axelsimon** [prakhar1989/docker-curriculum#97]
Hi,
First, thanks for a great tutorial!

You mention in the section [Docker Links](https://docker-curriculum.com/#docker-links) not to use links anymore and to replace it with network. But in the section on using docker compose on AWS, the docker-compose.yml example uses `links: -es` which I think requires an explanation (or at least an acknowledgement that it's contradictory to the previous advice).

Hope this helps fine tune the guide :)

**Comment by prakhar1989** [comment]
Updated [docker-compose](https://github.com/prakhar1989/FoodTrucks/blob/master/docker-compose.yml) to no longer have links =)

Thanks!
