### ISSUE TITLE
Web doesn't recognize es with Docker compose

### ISSUE THREAD

**Issue by vidyasagarps** [prakhar1989/docker-curriculum#99]
-- no entry for es in /etc/hosts of vidyasagarps/foodtrucks-web container

Vidyasagars-MacBook-Pro:SFFoodTrucks vps$ docker run -dp 9200:9200 --net foodtrucks --name es elasticsearch
5e93f9927b97007bbdc7d242a731e9ab85330b1793e116c76132798b8287e880

Vidyasagars-MacBook-Pro:SFFoodTrucks vps$ docker run -it --rm --net foodtrucks vidyasagarps/foodtrucks-web bash
root@f63a0091217f:/opt/flask-app# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.19.0.3	f63a0091217f
root@f63a0091217f:/opt/flask-app# exit

And with docker-compose they never bind together
Vidyasagars-MacBook-Pro:SFFoodTrucks vps$ docker stop 0da0b845e53f 5e93f9927b97

Vidyasagars-MacBook-Pro:SFFoodTrucks vps$ cat docker-compose.yml
version: "2"
services:
  es:
    image: elasticsearch
  web:
    image: vidyasagarps/foodtrucks-web
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code

Vidyasagars-MacBook-Pro:SFFoodTrucks vps$ docker-compose up
es_1   | [2017-11-09T06:41:34,508][INFO ][o.e.h.n.Netty4HttpServerTransport] [1kXzbGz] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
es_1   | [2017-11-09T06:41:34,508][INFO ][o.e.n.Node               ] [1kXzbGz] started
es_1   | [2017-11-09T06:41:34,559][INFO ][o.e.g.GatewayService     ] [1kXzbGz] recovered [0] indices into cluster_state
web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Unable to connect to ES. Retrying in 5 secs...
web_1  | Out of retries. Bailing out...
sffoodtrucks_web_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping sffoodtrucks_es_1 ... done
Vidyasagars-MacBook-Pro:SFFoodTrucks vps$

Am I missing any step here?

**Comment by thomasphillips3** [comment]
I had this same problem. Specifying the version for `elasticsearch` in the `docker-compose.yml` fixed it for me. The [tutorial](https://docker-curriculum.com) has

```
version: "2"
services:
  es:
    image: elasticsearch
...
```

But this works: 
```
version: "2"
services:
  es:
    image: elasticsearch:2.3
...
```

**Comment by xulz** [comment]
I got the same issue and find the cause: the latest elasticsearch took more that 15s to start so the web service exit.
I fix it by update flask-app/app.py line 31 to :
time.sleep(10).

Or just use the v2.3 es to load quicker.

**Comment by prakhar1989** [comment]
The [file](https://github.com/prakhar1989/FoodTrucks/blob/master/docker-compose.yml) has been updated with the version of es that should not have this problem. Let me know if that doesn't work.

**Comment by bibliolibs** [comment]
> I had this same problem. Specifying the version for `elasticsearch` in the `docker-compose.yml` fixed it for me. The [tutorial](https://docker-curriculum.com) has
> 
> ```
> version: "2"
> services:
>   es:
>     image: elasticsearch
> ...
> ```
> 
> But this works:
> 
> ```
> version: "2"
> services:
>   es:
>     image: elasticsearch:2.3
> ...
> ```

I encountered the same problem even with the updated file and this solution worked. Had me banging my head against the wall, thanks!

**Comment by hhummel** [comment]
I had the same problem with the new version of es. I found setting` time.sleep(15)` similar to what xulz said fixed it
